'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'is' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isHydrated: boolean;
}

const translations = {
  is: {
    // Navigation
    'nav.home': 'Heim',
    'nav.about': 'Um okkur',
    'nav.services': 'Þjónusta',
    'nav.contact': 'Hafa samband',
    'nav.start_now': 'Byrja núna',
    
    // Homepage
    'home.hero.title': 'Gleymdir afmælisdagur drepa stemningu',
    'home.hero.subtitle': 'Með StraxKaka er hver afmælisdagur munaður, hver kaka kemur á réttum tíma, og menning verður sætari.',
    'home.features.title': 'Hvað vinnur StraxKaka fyrir þig?',
    'home.features.subtitle': 'Við leysum vandamálið sem allir þekkja: gleymdir afmælisdagum sem skaða samstöðu og stemningu',
    'home.how_it_works.title': 'Svo einfalt er þetta',
    'home.how_it_works.subtitle': 'Þú skráir, við sérum um allt annað',
    'home.cta.title': 'Tilbúin/n að byrja?',
    'home.cta.subtitle': 'Hafðu samband við okkur í dag og fáðu að vita hvernig StraxKaka getur bætt stemninguna á vinnustaðnum þínum.',
    
    // Features
    'features.registration.title': 'Skráning án vandræða',
    'features.registration.desc': 'Hlaða inn Excel skrá eða tengja við HR kerfið. Engin flókin uppsetning, bara skrá og gleyma.',
    'features.ai.title': 'Við muna fyrir þig',
    'features.ai.desc': 'Kerfið muna allt: hver á afmælisdag, hvaða köku þeir vilja, og panta rétt á réttum tíma.',
    'features.delivery.title': 'Kökurnar koma til þín',
    'features.delivery.desc': 'Engin að fara í búð, engin að muna að panta. Kökurnar bara birtast á vinnustaðnum.',
    
    // How it works
    'how_it_works.step1.title': '1. Skrá starfsmenn',
    'how_it_works.step1.desc': 'Hlaða inn nöfn og afmælisdaga starfsmanna. Einn skjall og þú ert komin/n.',
    'how_it_works.step2.title': '2. Við muna fyrir þig',
    'how_it_works.step2.desc': 'Kerfið muna allt og panta kökur sjálfkrafa. Engin að gleyma neitt.',
    'how_it_works.step3.title': '3. Kökurnar birtast',
    'how_it_works.step3.desc': 'Á afmælisdaginn birtast kökurnar á vinnustaðnum. Starfsmenn fagna og stemningin batnar.',
    
    // Footer
    'footer.description': 'Lausn fyrir gleymdir afmælisdaga. Við muna fyrir þig.',
    'footer.services.title': 'Þjónusta',
    'footer.services.birthday': 'Afmælisdagaskráning',
    'footer.services.ai': 'AI sjálfvirkni',
    'footer.services.ordering': 'Kökupöntun',
    'footer.services.delivery': 'Afhending',
    'footer.company.title': 'Fyrirtæki',
    'footer.company.pricing': 'Verðskrá',
    'footer.company.blog': 'Blogg',
    'footer.contact.title': 'Hafa samband',
    'footer.legal.title': 'Löglegar síður',
    'footer.legal.privacy': 'Persónuverndarstefna',
    'footer.legal.terms': 'Skilmálar',
    'footer.legal.cookies': 'Vafrakökur',
    'footer.legal.legal': 'Löglegar upplýsingar',
    'footer.copyright': '© 2025 StraxKaka. Allur réttur áskilinn. Byrjaði árið 2025.',
    
    // Common
    'common.phone': '+354 790 4777',
    'common.email': 'orders.straxkaka@outlook.com',
    
    // About page
    'about.hero.title': 'Um okkur',
    'about.hero.subtitle': 'Lausn fyrir vandamálið sem allir þekkja: gleymdir afmælisdagum',
    'about.intro.title': 'Um okkur',
    'about.intro.desc': 'Í starfsmannadeildinni er nóg að gera – það þarf að muna afmælisdagsetningar, panta köku, sækja hana og bera fram. þetta getur verið auka stress eða þá gleymist þetta stundum. Það sem átti að vera gleðistund verður stress, og gleymdur afmælisdagur getur jafnvel skemmd vinnumorale.',
    'about.solution.title': 'Straxkaka er lausnin',
    'about.solution.desc': 'Við sjáum um allt ferlið – þú þarft ekki að lifta fingur. Enginn gleymir lengur, og fersk kaka birtist á vinnustaðnum á afmælisdaginn.',
    'about.why.title': 'Af hverju Straxkaka?',
    'about.why.no_forgotten.title': 'Engin gleymd afmæli',
    'about.why.no_forgotten.desc': 'Við höldum utan um dagsetningarnar.',
    'about.why.zero_hassle.title': 'Engin fyrirhöfn fyrir HR eða stjórnendur',
    'about.why.zero_hassle.desc': 'Við pöntum, samræmum og sendum kökuna.',
    'about.why.culture.title': 'Betri starfsandi',
    'about.why.culture.desc': 'Smáatriði skipta máli – að fagna afmælum eflir samhug, hvetur starfsfólk og styrkir menningu á vinnustaðnum.',
    'about.promise.title': 'Okkar loforð',
    'about.promise.desc': 'Við vinnum með traustum bakaríum sem nota hágæða hráefni. Kökurnar eru bakaðar af alúð og afhentar á réttum tíma – alltaf tilbúnar til að gleðja.',
    'about.future.title': 'Framtíðin',
    'about.future.desc': 'Straxkaka er meira en bara kaka. Við erum að byggja upp framtíð vinnustaðarmenningar þar sem enginn afmælisdagur er gleymdur og enginn starfsmaður vanmetinn.',
    'about.team.title': 'Teymið okkar',
    'about.team.desc': 'Hæ, ég heiti Bjarki og er stofnandi Straxköku. Ég er 20 ára og byrjaði fyrirtækið með einfalt markmið: að gera afmælisdaginn á vinnustaðnum auðveldari og skemmtilegri. Ég veit hvað það getur verið stressandi þegar afmæli gleymist, svo ég vildi búa til þjónustu þar sem enginn þarf að hafa áhyggjur – kakan mætir bara á réttum tíma. Ég vinn með góðum bakaríum til að tryggja góða þjónustu og legg áherslu á að ferlið sé áreiðanlegt, vingjarnlegt og áhyggjulaust.',
    'about.cta.title': 'Tilbúin/n að byrja?',
    'about.cta.subtitle': 'Hafðu samband við okkur og fáðu að vita hvernig StraxKaka getur bætt stemninguna á vinnustaðnum þínum.',
    'about.cta.subscribe': 'Byrja áskrift',
    'about.cta.contact': 'Hafa samband',
    
    // Subscribe page
    'nav.subscription': 'Áskrift',
    'subscribe.hero.title': 'Skráðu starfsmenn fyrirtækisins þíns',
    'subscribe.hero.subtitle': 'Byrjaðu að nota StraxKaka í dag og gleymdu aldrei afmælisdögum starfsmanna',
    'subscribe.company.title': 'Upplýsingar um fyrirtækið',
    'subscribe.company.name': 'Nafn fyrirtækis',
    'subscribe.company.contact_name': 'Nafn tengiliðs',
    'subscribe.company.email': 'Netfang',
    'subscribe.company.phone': 'Símanúmer',
    'subscribe.company.address': 'Heimilisfang fyrir afhendingu',
    'subscribe.employees.title': 'Starfsmenn',
    'subscribe.employees.add': 'Bæta við starfsmanni',
    'subscribe.employees.employee': 'Starfsmaður',
    'subscribe.employees.remove': 'Fjarlægja',
    'subscribe.employees.name': 'Nafn',
    'subscribe.employees.birthday': 'Afmælisdagur',
    'subscribe.employees.cake_type': 'Tegund köku',
    'subscribe.employees.dietary': 'Matarheftir',
    'subscribe.employees.notes': 'Sérstakar athugasemdir',
    'subscribe.employees.file_upload': 'Hlaða upp skrá',
    'subscribe.submit': 'Skrá fyrirtæki',
    'subscribe.submitting': 'Skrái...',
    'subscribe.success.title': 'Takk fyrir skráninguna!',
    'subscribe.success.message': 'Við höfum móttekið upplýsingarnar um starfsmenn fyrirtækisins þíns. Við höfum samband innan 24 klukkustunda til að ræða næstu skref.',
    'subscribe.success.back_home': 'Til baka á heimasíðuna',
    'subscribe.success.view_submissions': 'Skoða skráningar (fyrir stjórnendur)',
    
    // Admin page
    'admin.loading': 'Hleð gögnum...',
    'admin.title': 'Stjórnendadashboard',
    'admin.subtitle': 'Skoða og stjórna skráningum fyrirtækja og starfsmanna',
    'admin.stats.companies': 'Fyrirtæki',
    'admin.stats.employees': 'Starfsmenn',
    'admin.stats.upcoming': 'Kemur afmæli næstu 30 daga',
    'admin.stats.average': 'Meðaltal starfsmanna',
    'admin.upcoming.title': 'Kemur afmæli næstu 30 daga',
    'admin.upcoming.cake_type': 'Tegund köku',
    'admin.upcoming.today': 'Í dag!',
    'admin.upcoming.days': 'daga',
    'admin.search.title': 'Leita',
    'admin.search.company': 'Fyrirtækið',
    'admin.search.all': 'Allir',
    'admin.export': 'Flytja út CSV',
    'admin.submissions.title': 'Skráningar',
    'admin.submissions.empty': 'Engar skráningar fundust',
    'admin.table.company': 'Fyrirtækið',
    'admin.table.contact': 'Tengiliður',
    'admin.table.employees': 'Starfsmenn',
    'admin.table.date': 'Dagsetning',
    'admin.table.actions': 'Aðgerðir',
    'admin.table.employees_count': 'starfsmenn',
    'admin.table.view': 'Skoða',
    'admin.modal.company_info': 'Upplýsingar um fyrirtækið',
    'admin.modal.contact': 'Tengiliður',
    'admin.modal.phone': 'Sími',
    'admin.modal.address': 'Heimilisfang',
    'admin.modal.employees': 'Starfsmenn',
    'admin.modal.birthday': 'Afmælisdagur',
    'admin.modal.cake_type': 'Tegund köku',
    'admin.modal.dietary': 'Matarheftir',
    'admin.modal.notes': 'Athugasemdir',
    
    // CSV Upload
    'csv.upload.title': 'Hlaða upp CSV skrá',
    'csv.upload.subtitle': 'Hlaða upp CSV skrá með starfsmönnum fyrir fljótlega skráningu',
    'csv.upload.download_template': 'Sækja sniðmát',
    'csv.upload.processing': 'Vinnur...',
    'csv.upload.select_file': 'Velja CSV skrá',
    'csv.preview.title': 'Forskoðun CSV gögn',
    'csv.preview.confirm': 'Staðfesta',
    'csv.preview.cancel': 'Hætta við',
    'csv.preview.valid': 'Gildir',
    'csv.preview.invalid': 'Ógildir',
    'csv.preview.row': 'Röð',
    'csv.preview.name': 'Nafn',
    'csv.preview.birthday': 'Afmælisdagur',
    'csv.preview.cake_type': 'Tegund köku',
    'csv.preview.status': 'Staða',
    'csv.success.employees_added': 'starfsmenn bætt við',
    'csv.errors.insufficient_columns': 'Ófullnægjandi dálkar',
    'csv.errors.name_required': 'Nafn er nauðsynlegt',
    'csv.errors.birthday_required': 'Afmælisdagur er nauðsynlegur',
    'csv.errors.invalid_birthday': 'Ógildur afmælisdagur',
    'csv.errors.cake_type_required': 'Tegund köku er nauðsynleg',
    'csv.errors.invalid_file_type': 'Ógild skráartegund. Vinsamlegast veldu CSV skrá.',
    'csv.errors.parse_error': 'Villa við að þýða CSV skrá',
    'csv.errors.read_error': 'Villa við að lesa skrá',
    'csv.errors.no_valid_rows': 'Engar gildar raðir fundust',
    
    // Enhanced File Upload
    'file.upload.title': 'Hlaða upp skrá með starfsmönnum',
    'file.upload.subtitle': 'Stuðningur við CSV, Excel (.xlsx) og Google Sheets',
    'file.upload.download_csv': 'Sækja CSV sniðmát',
    'file.upload.download_excel': 'Sækja Excel sniðmát',
    'file.upload.open_google_sheets': 'Opna Google Sheets',
    'file.upload.processing': 'Vinnur...',
    'file.upload.select_file': 'Velja skrá',
    'file.upload.supported_formats': 'CSV, Excel (.xlsx, .xls)',
    'file.preview.title': 'Forskoðun skrárgögn',
    'file.preview.confirm': 'Staðfesta',
    'file.preview.cancel': 'Hætta við',
    'file.preview.valid': 'Gildir',
    'file.preview.invalid': 'Ógildir',
    'file.preview.row': 'Röð',
    'file.preview.name': 'Nafn',
    'file.preview.birthday': 'Afmælisdagur',
    'file.preview.cake_type': 'Tegund köku',
    'file.preview.status': 'Staða',
    'file.success.employees_added': 'starfsmenn bætt við',
    'file.errors.insufficient_columns': 'Ófullnægjandi dálkar',
    'file.errors.name_required': 'Nafn er nauðsynlegt',
    'file.errors.birthday_required': 'Afmælisdagur er nauðsynlegur',
    'file.errors.invalid_birthday': 'Ógildur afmælisdagur',
    'file.errors.cake_type_required': 'Tegund köku er nauðsynleg',
    'file.errors.invalid_file_type': 'Ógild skráartegund. Vinsamlegast veldu CSV eða Excel skrá.',
    'file.errors.csv_parse_error': 'Villa við að þýða CSV skrá',
    'file.errors.excel_parse_error': 'Villa við að þýða Excel skrá',
    'file.errors.read_error': 'Villa við að lesa skrá',
    'file.errors.no_valid_rows': 'Engar gildar raðir fundust',
    'file.errors.unknown_error': 'Óþekkt villa',
    'file.errors.excel_import_error': 'Villa við að hlaða inn Excel bókunni',
    'file.errors.download_error': 'Villa við að sækja sniðmát',
    
    // Subscription System
    'subscription.loading': 'Hleð gögnum...',
    'subscription.steps.company': 'Upplýsingar um fyrirtækið',
    'subscription.steps.employees': 'Starfsmenn',
    'subscription.steps.subscription': 'Áskrift',
    'subscription.steps.payment': 'Greiðsla',
    'subscription.company.title': 'Upplýsingar um fyrirtækið',
    'subscription.company.name': 'Nafn fyrirtækis',
    'subscription.company.contact_name': 'Nafn tengiliðs',
    'subscription.company.email': 'Netfang',
    'subscription.company.phone': 'Símanúmer',
    'subscription.company.address': 'Heimilisfang fyrir afhendingu',
    'subscription.employees.title': 'Starfsmenn',
    'subscription.employees.file_upload': 'Hlaða upp skrá',
    'subscription.employees.add': 'Bæta við starfsmanni',
    'subscription.employees.employee': 'Starfsmaður',
    'subscription.employees.remove': 'Fjarlægja',
    'subscription.employees.name': 'Nafn',
    'subscription.employees.birthday': 'Afmælisdagur',
    'subscription.employees.birthday_hint': 'Smelltu á reitinn til að velja dagsetningu',
    'subscription.employees.cake_type': 'Tegund köku',
    'subscription.employees.cake_size': 'Stærð köku',
    'subscription.employees.dietary': 'Matarheftir',
    'subscription.employees.notes': 'Sérstakar athugasemdir',
    'subscription.navigation.back': 'Til baka',
    'subscription.navigation.next': 'Áfram',
    'subscription.navigation.submit': 'Skrá áskrift',
    'subscription.navigation.submitting': 'Skrái...',
    'subscription.success.title': 'Takk fyrir skráninguna!',
    'subscription.success.message': 'Við höfum móttekið áskriftarbeiðni fyrir fyrirtækið þitt. Við höfum samband innan 24 klukkustunda til að ræða greiðslu og næstu skref.',
    'subscription.success.back_home': 'Til baka á heimasíðuna',
    'subscription.success.view_subscriptions': 'Skoða áskriftir (fyrir stjórnendur)',
    'subscription.success.employees_added': 'starfsmenn bætt við',
    'subscription.errors.company_name_required': 'Nafn fyrirtækis er nauðsynlegt',
    'subscription.errors.invalid_email': 'Ógilt netfang',
    'subscription.errors.invalid_phone': 'Ógilt símanúmer',
    'subscription.errors.address_required': 'Heimilisfang fyrir afhendingu er nauðsynlegt',
    'subscription.errors.no_employees': 'Að minnsta kosti einn starfsmaður er nauðsynlegur',
    'subscription.errors.employee_name_required': 'Nafn starfsmanns er nauðsynlegt',
    'subscription.errors.birthday_required': 'Afmælisdagur er nauðsynlegur',
    'subscription.errors.invalid_birthday': 'Ógildur afmælisdagur',
    'subscription.errors.cake_type_required': 'Tegund köku er nauðsynleg',
    'subscription.errors.tier_required': 'Vinsamlegast veldu áskriftarstig',
    'subscription.errors.submission_failed': 'Villa við skráningu. Vinsamlegast reyndu aftur.',
    
    // Payment step
    'subscription.payment.title': 'Greiðsla',
    'subscription.payment.summary': 'Pöntunaryfirlit',
    'subscription.payment.company': 'Fyrirtækið',
    'subscription.payment.tier': 'Áskriftarstig',
    'subscription.payment.employee_count': 'Fjöldi starfsmanna',
    'subscription.payment.monthly_cost': 'Mánaðargjald',
    'subscription.payment.method': 'Greiðslumáti',
    'subscription.payment.aur.title': 'AUR greiðsla',
    'subscription.payment.aur.description': 'Greiðsla verður send á símanúmerið þitt: {phone}',
    'subscription.payment.aur.sms_note': 'Þú færð SMS með hlekk til að ljúka greiðslunni',
    'subscription.payment.bank_transfer.title': 'Bankagreiðsla',
    'subscription.payment.bank_transfer.description': 'Fáðu bankaupplýsingar og einstakt viðmiðunarnúmer fyrir greiðslu',
    'subscription.payment.bank_transfer.activation_note': 'Áskriftin verður virkjuð þegar greiðslan er staðfest',
    'subscription.payment.bank_transfer.success_message': 'Bankaupplýsingar hefur verið búið til. Vinsamlegast ljúktu bankagreiðslunni til að virkja áskriftina.',
    'subscription.payment.bank_transfer.instructions': 'Bankagreiðsluupplýsingar',
    'subscription.payment.bank_transfer.bank_name': 'Banki',
    'subscription.payment.bank_transfer.account_number': 'Reikningsnúmer',
    'subscription.payment.bank_transfer.reference': 'Viðmiðunarnúmer',
    'subscription.payment.bank_transfer.amount': 'Upphæð',
    'subscription.payment.bank_transfer.note': 'Vinsamlegast ljúktu bankagreiðslunni. Áskriftin verður virkjuð þegar greiðslan er staðfest.',
    'subscription.payment.bank_transfer.success_title': 'Bankaupplýsingar búnar til!',
    'subscription.payment.terms': 'Ég samþykki að greiða mánaðarlega greiðslu fyrir StraxKaka þjónustuna og skil að hægt er að hætta hvenær sem er.',
    'subscription.payment.success_message': 'Greiðslubeiðni hefur verið send á símanúmerið þitt. Vinsamlegast ljúktu greiðslunni til að virkja áskriftina.',
    'subscription.payment.success_title': 'Greiðslubeiðni send!',
    'subscription.payment.phone_number': 'Símanúmer',
    'subscription.navigation.processing': 'Greiði...',
    'subscription.navigation.pay_now': 'Greiða núna',
    
    // Pricing
    'pricing.title': 'Verðskrá',
    'pricing.subtitle': 'Veldu þá áskriftarstig sem hentar fyrirtækinu þínu',
    'pricing.recommended': 'Mælt með',
    'pricing.per_month': 'á mánuði',
    'pricing.employees': 'starfsmenn',
    'pricing.suitable': 'Hentar fyrir fyrirtækið þitt',
    'pricing.not_suitable': 'Ekki hentar fyrir fyrirtækið þitt',
    'pricing.selected': 'Valið',
    'pricing.select': 'Velja',
    'pricing.for_your_company': 'Fyrir fyrirtækið þitt',
    'pricing.for': 'Fyrir',
    'pricing.disclaimer': 'Allar verðir eru með 24% VSK. Engin uppsetningargjald. Hægt að hætta hvenær sem er.',
    'pricing.tiers.small.name': 'Lítill',
    'pricing.tiers.small.description': 'Hentar fyrir litla teymi',
    'pricing.tiers.medium.name': 'Meðalstór',
    'pricing.tiers.medium.description': 'Hentar fyrir vaxandi fyrirtæki',
    'pricing.tiers.large.name': 'Stór',
    'pricing.tiers.large.description': 'Hentar fyrir stofnuð fyrirtæki',
    'pricing.tiers.enterprise.name': 'Fyrirtæki',
    'pricing.tiers.enterprise.description': 'Sérsniðið verð fyrir stórar stofnanir',
    'pricing.tiers.enterprise.price': 'Sérsniðið',
    
    // Dashboard
    'dashboard.loading': 'Hleð gögnum...',
    'dashboard.title': 'Stjórnendadashboard',
    'dashboard.subtitle': 'Skoða og stjórna áskriftum og greiðslum',
    'dashboard.stats.companies': 'Fyrirtæki',
    'dashboard.stats.active': 'Aktívar áskriftir',
    'dashboard.stats.pending': 'Bíður greiðslu',
    'dashboard.stats.revenue': 'Mánaðartekjur',
    'dashboard.companies.title': 'Fyrirtæki',
    'dashboard.companies.company': 'Fyrirtæki',
    'dashboard.companies.status': 'Staða',
    'dashboard.companies.monthly_cost': 'Mánaðargjald',
    'dashboard.companies.employees': 'Starfsmenn',
    'dashboard.companies.next_payment': 'Næsta greiðsla',
    'dashboard.payments.title': 'Nýlegar greiðslur',
    'dashboard.payments.order': 'Pöntun',
    'dashboard.payments.amount': 'Upphæð',
    'dashboard.payments.status': 'Staða',
    'dashboard.payments.date': 'Dagsetning',
    'dashboard.status.active': 'Virk',
    'dashboard.status.pending_payment': 'Bíður greiðslu',
    'dashboard.status.suspended': 'Í bið',
    'dashboard.status.cancelled': 'Hætt',
    'dashboard.payment_status.completed': 'Lokið',
    'dashboard.payment_status.processing': 'Vinnur',
    'dashboard.payment_status.failed': 'Mistókst',
    'dashboard.payment_status.pending': 'Bíður',
    
    // Services page
    'services.hero.title': 'Hvað vinnur StraxKaka fyrir þig?',
    'services.hero.subtitle': 'Við leysum vandamálið sem allir þekkja: gleymdir afmælisdagum sem skaða samstöðu og stemningu',
    'services.cta.title': 'Tilbúin/n að byrja?',
    'services.cta.subtitle': 'Hafðu samband við okkur og fáðu að vita hvernig StraxKaka getur bætt stemninguna á vinnustaðnum þínum.',
    'services.cta.subscribe': 'Byrja áskrift',
    'services.cta.contact': 'Hafa samband',
    
    // Services features
    'services.registration.feature1': 'Einföld skráning',
    'services.registration.feature2': 'Hlaða inn Excel skrá',
    'services.registration.feature3': 'Engin flókin uppsetning',
    'services.registration.feature4': 'Örugg gagnavörn',
    'services.ai.desc': 'Kerfið muna allt fyrir þig: hver á afmælisdag, hvaða köku þeir vilja, og panta rétt á réttum tíma. Engin að gleyma neitt.',
    'services.ai.feature1': 'Við muna fyrir þig',
    'services.ai.feature2': 'Sjálfvirk kökupöntun',
    'services.ai.feature3': 'Tilkynningar til þín',
    'services.ai.feature4': 'Engin gleymdir',
    'services.delivery.desc': 'Við vinnum með góðum kökubúðum og sjáum um að kökurnar komi á vinnustaðinn á réttum tíma. Engin að fara í búð.',
    'services.delivery.feature1': 'Góðar kökubúðir',
    'services.delivery.feature2': 'Kökurnar koma til þín',
    'services.delivery.feature3': 'Margir valkostir',
    'services.delivery.feature4': 'Áreiðanleg þjónusta',
    
    // Contact page
    'contact.hero.title': 'Hafa samband',
    'contact.hero.subtitle': 'Hafðu samband við okkur og fáðu að vita hvernig StraxKaka getur bætt stemninguna á vinnustaðnum þínum',
    'contact.form.title': 'Sendu okkur skilaboð',
    'contact.form.name': 'Nafn',
    'contact.form.email': 'Netfang',
    'contact.form.company': 'Fyrirtæki',
    'contact.form.phone': 'Sími',
    'contact.form.message': 'Skilaboð',
    'contact.form.submit': 'Senda skilaboð',
    'contact.form.validation.required': 'Vinsamlegast fylltu út allar nauðsynlegar reiti.',
    'contact.form.success': 'Takk fyrir skilaboðin! Við höfum samband innan 24 klukkustunda.',
    'contact.form.error': 'Villa kom upp við að senda skilaboðin. Vinsamlegast reyndu aftur.',
    'contact.info.title': 'Upplýsingar',
    'contact.faq.title': 'Algengar spurningar',
    'contact.faq.q1.question': 'Hvað kostar þjónustan?',
    'contact.faq.q1.answer': 'Verðið fer eftir fjölda starfsmanna. Hafðu samband fyrir nákvæma verðskrá.',
    'contact.faq.q2.question': 'Hvaða HR kerfi vinnur StraxKaka með?',
    'contact.faq.q2.answer': 'Við vinnum með flestum helstu HR kerfum á Íslandi. Hafðu samband til að athuga hvort kerfið ykkar sé í boði.',
    'contact.faq.q3.question': 'Hvaða kökubúðir vinnið þið með?',
    'contact.faq.q3.answer': 'Við vinnum með bestu kökubúðunum á Íslandi og getum boðið upp á margar mismunandi valkosti.',
    'contact.info.email.title': 'Netfang',
    'contact.info.email.desc': 'orders.straxkaka@outlook.com',
    'contact.info.email.note': 'svarum innan 24 klukkustunda',
    'contact.info.phone.title': 'Sími',
    'contact.info.phone.desc': '+354 790 4777',
    'contact.info.phone.note': 'Mán-fös: 09:00-17:00',
    'contact.info.orders.title': 'Pöntun',
    'contact.info.orders.desc': 'orders.straxkaka@outlook.com',
    'contact.info.orders.note': 'fyrir pöntanir og spurningar',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.start_now': 'Get Started',
    
    // Homepage
    'home.hero.title': 'Never Forget Employee Birthdays Again',
    'home.hero.subtitle': 'AI automation that orders cakes for company employees so no one forgets birthdays. StraxKaka handles everything - from registration to delivery.',
    'home.features.title': 'What does StraxKaka do?',
    'home.features.subtitle': 'We automate the birthday cake process for your company',
    'home.how_it_works.title': 'How does it work?',
    'home.how_it_works.subtitle': 'Simple process in 3 steps',
    'home.cta.title': 'Ready to get started?',
    'home.cta.subtitle': 'Contact us today and get a free consultation on how StraxKaka can help your company.',
    
    // Features
    'features.registration.title': 'Birthday Registration',
    'features.registration.desc': 'We connect to your HR system and transfer all birthday information to our secure system.',
    'features.ai.title': 'AI Automation',
    'features.ai.desc': 'Our artificial intelligence handles ordering the right cake for the right employee at the right time.',
    'features.delivery.title': 'Delivery',
    'features.delivery.desc': 'Cakes are delivered directly to the workplace on the birthday.',
    
    // How it works
    'how_it_works.step1.title': '1. Connect HR System',
    'how_it_works.step1.desc': 'We connect to your HR system and transfer birthday information.',
    'how_it_works.step2.title': '2. AI Orders Cakes',
    'how_it_works.step2.desc': 'Our artificial intelligence automatically orders cakes for birthdays.',
    'how_it_works.step3.title': '3. Delivery',
    'how_it_works.step3.desc': 'Cakes are delivered to the workplace on the birthday.',
    
    // Footer
    'footer.description': 'AI automation for birthday cakes for Icelandic companies.',
    'footer.services.title': 'Services',
    'footer.services.birthday': 'Birthday Registration',
    'footer.services.ai': 'AI Automation',
    'footer.services.ordering': 'Cake Ordering',
    'footer.services.delivery': 'Delivery',
    'footer.company.title': 'Company',
    'footer.company.pricing': 'Pricing',
    'footer.company.blog': 'Blog',
    'footer.contact.title': 'Contact',
    'footer.legal.title': 'Legal Pages',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms of Service',
    'footer.legal.cookies': 'Cookie Policy',
    'footer.legal.legal': 'Legal Information',
    'footer.copyright': '© 2025 StraxKaka. All rights reserved. Started in 2025.',
    
    // Common
    'common.phone': '+354 790 4777',
    'common.email': 'orders.straxkaka@outlook.com',
    
    // About page
    'about.hero.title': 'About StraxKaka',
    'about.hero.subtitle': 'AI automation for birthday cakes for companies',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To make employee birthdays unforgettable with AI automation.',
    'about.mission.desc2': 'I started this project in 2025 to help companies never forget employee birthdays with AI automation.',
    'about.project.title': 'New Project',
    'about.project.desc': 'In development for Icelandic companies',
    'about.team.title': 'The Team',
    'about.team.desc': 'I am a one-person team who started this project to help companies never forget employee birthdays.',
    'about.founder.title': 'Founder',
    'about.founder.tagline': 'One person, big dream',
    'about.founder.desc': 'I am one person who started this project in 2025 to help companies never forget employee birthdays with AI automation.',
    'about.values.title': 'Our Values',
    'about.values.desc': 'Simplicity, reliability, and personal service.',
    'about.values.cooperation.title': 'Cooperation',
    'about.values.cooperation.desc': 'We work closely with companies and bakeries to ensure the best service.',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.desc': 'We use the latest technology to make the process as simple and automated as possible.',
    'about.values.care.title': 'Care',
    'about.values.care.desc': 'We care that employees get to celebrate their birthday at the workplace.',
    'about.values.quality.title': 'Quality',
    'about.values.quality.desc': 'We ensure only the best quality in everything we do - from cakes to service.',
    'about.cta.title': 'Ready to Get Started?',
    'about.cta.subtitle': 'Join the companies already using StraxKaka to never miss an employee birthday again.',
    'about.cta.subscribe': 'Start Subscription',
    'about.cta.contact': 'Contact Us',
    
    // Subscribe page
    'nav.subscription': 'Subscription',
    'subscribe.hero.title': 'Register Your Company Employees',
    'subscribe.hero.subtitle': 'Start using StraxKaka today and never forget employee birthdays',
    'subscribe.company.title': 'Company Information',
    'subscribe.company.name': 'Company Name',
    'subscribe.company.contact_name': 'Contact Person Name',
    'subscribe.company.email': 'Email',
    'subscribe.company.phone': 'Phone Number',
    'subscribe.company.address': 'Delivery Address',
    'subscribe.employees.title': 'Employees',
    'subscribe.employees.add': 'Add Employee',
    'subscribe.employees.employee': 'Employee',
    'subscribe.employees.remove': 'Remove',
    'subscribe.employees.name': 'Name',
    'subscribe.employees.birthday': 'Birthday',
    'subscribe.employees.cake_type': 'Cake Type',
    'subscribe.employees.dietary': 'Dietary Restrictions',
    'subscribe.employees.notes': 'Special Notes',
    'subscribe.employees.file_upload': 'Upload File',
    'subscribe.submit': 'Register Company',
    'subscribe.submitting': 'Submitting...',
    'subscribe.success.title': 'Thank you for registering!',
    'subscribe.success.message': 'We have received the information about your company employees. We will contact you within 24 hours to discuss next steps.',
    'subscribe.success.back_home': 'Back to Homepage',
    'subscribe.success.view_submissions': 'View Submissions (Admin)',
    
    // Admin page
    'admin.loading': 'Loading data...',
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'View and manage company and employee registrations',
    'admin.stats.companies': 'Companies',
    'admin.stats.employees': 'Employees',
    'admin.stats.upcoming': 'Birthdays in next 30 days',
    'admin.stats.average': 'Average employees',
    'admin.upcoming.title': 'Birthdays in next 30 days',
    'admin.upcoming.cake_type': 'Cake Type',
    'admin.upcoming.today': 'Today!',
    'admin.upcoming.days': 'days',
    'admin.search.title': 'Search',
    'admin.search.company': 'Company',
    'admin.search.all': 'All',
    'admin.export': 'Export CSV',
    'admin.submissions.title': 'Submissions',
    'admin.submissions.empty': 'No submissions found',
    'admin.table.company': 'Company',
    'admin.table.contact': 'Contact',
    'admin.table.employees': 'Employees',
    'admin.table.date': 'Date',
    'admin.table.actions': 'Actions',
    'admin.table.employees_count': 'employees',
    'admin.table.view': 'View',
    'admin.modal.company_info': 'Company Information',
    'admin.modal.contact': 'Contact',
    'admin.modal.phone': 'Phone',
    'admin.modal.address': 'Address',
    'admin.modal.employees': 'Employees',
    'admin.modal.birthday': 'Birthday',
    'admin.modal.cake_type': 'Cake Type',
    'admin.modal.dietary': 'Dietary Restrictions',
    'admin.modal.notes': 'Notes',
    
    // CSV Upload
    'csv.upload.title': 'Upload CSV File',
    'csv.upload.subtitle': 'Upload a CSV file with employees for quick registration',
    'csv.upload.download_template': 'Download Template',
    'csv.upload.processing': 'Processing...',
    'csv.upload.select_file': 'Select CSV File',
    'csv.preview.title': 'CSV Data Preview',
    'csv.preview.confirm': 'Confirm',
    'csv.preview.cancel': 'Cancel',
    'csv.preview.valid': 'Valid',
    'csv.preview.invalid': 'Invalid',
    'csv.preview.row': 'Row',
    'csv.preview.name': 'Name',
    'csv.preview.birthday': 'Birthday',
    'csv.preview.cake_type': 'Cake Type',
    'csv.preview.status': 'Status',
    'csv.success.employees_added': 'employees added',
    'csv.errors.insufficient_columns': 'Insufficient columns',
    'csv.errors.name_required': 'Name is required',
    'csv.errors.birthday_required': 'Birthday is required',
    'csv.errors.invalid_birthday': 'Invalid birthday',
    'csv.errors.cake_type_required': 'Cake type is required',
    'csv.errors.invalid_file_type': 'Invalid file type. Please select a CSV file.',
    'csv.errors.parse_error': 'Error parsing CSV file',
    'csv.errors.read_error': 'Error reading file',
    'csv.errors.no_valid_rows': 'No valid rows found',
    
    // Enhanced File Upload
    'file.upload.title': 'Upload File with Employees',
    'file.upload.subtitle': 'Support for CSV, Excel (.xlsx) and Google Sheets',
    'file.upload.download_csv': 'Download CSV Template',
    'file.upload.download_excel': 'Download Excel Template',
    'file.upload.open_google_sheets': 'Open Google Sheets',
    'file.upload.processing': 'Processing...',
    'file.upload.select_file': 'Select File',
    'file.upload.supported_formats': 'CSV, Excel (.xlsx, .xls)',
    'file.preview.title': 'File Data Preview',
    'file.preview.confirm': 'Confirm',
    'file.preview.cancel': 'Cancel',
    'file.preview.valid': 'Valid',
    'file.preview.invalid': 'Invalid',
    'file.preview.row': 'Row',
    'file.preview.name': 'Name',
    'file.preview.birthday': 'Birthday',
    'file.preview.cake_type': 'Cake Type',
    'file.preview.status': 'Status',
    'file.success.employees_added': 'employees added',
    'file.errors.insufficient_columns': 'Insufficient columns',
    'file.errors.name_required': 'Name is required',
    'file.errors.birthday_required': 'Birthday is required',
    'file.errors.invalid_birthday': 'Invalid birthday',
    'file.errors.cake_type_required': 'Cake type is required',
    'file.errors.invalid_file_type': 'Invalid file type. Please select a CSV or Excel file.',
    'file.errors.csv_parse_error': 'Error parsing CSV file',
    'file.errors.excel_parse_error': 'Error parsing Excel file',
    'file.errors.read_error': 'Error reading file',
    'file.errors.no_valid_rows': 'No valid rows found',
    'file.errors.unknown_error': 'Unknown error',
    'file.errors.excel_import_error': 'Error importing Excel library',
    'file.errors.download_error': 'Error downloading template',
    
    // Subscription System
    'subscription.loading': 'Loading data...',
    'subscription.steps.company': 'Company Information',
    'subscription.steps.employees': 'Employees',
    'subscription.steps.subscription': 'Subscription',
    'subscription.steps.payment': 'Payment',
    'subscription.company.title': 'Company Information',
    'subscription.company.name': 'Company Name',
    'subscription.company.contact_name': 'Contact Person Name',
    'subscription.company.email': 'Email',
    'subscription.company.phone': 'Phone Number',
    'subscription.company.address': 'Delivery Address',
    'subscription.employees.title': 'Employees',
    'subscription.employees.file_upload': 'Upload File',
    'subscription.employees.add': 'Add Employee',
    'subscription.employees.employee': 'Employee',
    'subscription.employees.remove': 'Remove',
    'subscription.employees.name': 'Name',
    'subscription.employees.birthday': 'Birthday',
    'subscription.employees.birthday_hint': 'Click the field to select a date',
    'subscription.employees.cake_type': 'Cake Type',
    'subscription.employees.cake_size': 'Cake Size',
    'subscription.employees.dietary': 'Dietary Restrictions',
    'subscription.employees.notes': 'Special Notes',
    'subscription.navigation.back': 'Back',
    'subscription.navigation.next': 'Next',
    'subscription.navigation.submit': 'Submit Subscription',
    'subscription.navigation.submitting': 'Submitting...',
    'subscription.success.title': 'Thank you for registering!',
    'subscription.success.message': 'We have received your subscription request. We will contact you within 24 hours to discuss payment and next steps.',
    'subscription.success.back_home': 'Back to Homepage',
    'subscription.success.view_subscriptions': 'View Subscriptions (Admin)',
    'subscription.success.employees_added': 'employees added',
    'subscription.errors.company_name_required': 'Company name is required',
    'subscription.errors.invalid_email': 'Invalid email address',
    'subscription.errors.invalid_phone': 'Invalid phone number',
    'subscription.errors.address_required': 'Delivery address is required',
    'subscription.errors.no_employees': 'At least one employee is required',
    'subscription.errors.employee_name_required': 'Employee name is required',
    'subscription.errors.birthday_required': 'Birthday is required',
    'subscription.errors.invalid_birthday': 'Invalid birthday',
    'subscription.errors.cake_type_required': 'Cake type is required',
    'subscription.errors.tier_required': 'Please select a subscription tier',
    'subscription.errors.submission_failed': 'Submission failed. Please try again.',
    
    // Payment step
    'subscription.payment.title': 'Payment',
    'subscription.payment.summary': 'Order Summary',
    'subscription.payment.company': 'Company',
    'subscription.payment.tier': 'Subscription Tier',
    'subscription.payment.employee_count': 'Number of Employees',
    'subscription.payment.monthly_cost': 'Monthly Cost',
    'subscription.payment.method': 'Payment Method',
    'subscription.payment.aur.title': 'Aur Payment',
    'subscription.payment.aur.description': 'Payment will be sent to your phone number: {phone}',
    'subscription.payment.aur.sms_note': 'You will receive an SMS with a link to complete the payment',
    'subscription.payment.bank_transfer.title': 'Bank Transfer',
    'subscription.payment.bank_transfer.description': 'Get bank details and unique reference number for payment',
    'subscription.payment.bank_transfer.activation_note': 'Subscription will be activated once payment is confirmed',
    'subscription.payment.bank_transfer.success_message': 'Bank details have been generated. Please complete the bank transfer to activate your subscription.',
    'subscription.payment.bank_transfer.instructions': 'Bank Transfer Instructions',
    'subscription.payment.bank_transfer.bank_name': 'Bank',
    'subscription.payment.bank_transfer.account_number': 'Account Number',
    'subscription.payment.bank_transfer.reference': 'Reference Number',
    'subscription.payment.bank_transfer.amount': 'Amount',
    'subscription.payment.bank_transfer.note': 'Please complete the bank transfer. Your subscription will be activated once payment is confirmed.',
    'subscription.payment.bank_transfer.success_title': 'Bank Details Generated!',
    'subscription.payment.terms': 'I agree to pay monthly fees for StraxKaka service and understand that I can cancel anytime.',
    'subscription.payment.success_message': 'Payment request has been sent to your phone number. Please complete the payment to activate your subscription.',
    'subscription.payment.success_title': 'Payment Request Sent!',
    'subscription.payment.phone_number': 'Phone Number',
    'subscription.navigation.processing': 'Processing...',
    'subscription.navigation.pay_now': 'Pay Now',
    
    // Pricing
    'pricing.title': 'Pricing',
    'pricing.subtitle': 'Choose the subscription tier that fits your company',
    'pricing.recommended': 'Recommended',
    'pricing.per_month': 'per month',
    'pricing.employees': 'employees',
    'pricing.suitable': 'Suitable for your company',
    'pricing.not_suitable': 'Not suitable for your company',
    'pricing.selected': 'Selected',
    'pricing.select': 'Select',
    'pricing.for_your_company': 'For your company',
    'pricing.for': 'For',
    'pricing.disclaimer': 'All prices include 24% VAT. No setup fee. Cancel anytime.',
    'pricing.tiers.small.name': 'Small',
    'pricing.tiers.small.description': 'Perfect for small teams',
    'pricing.tiers.medium.name': 'Medium',
    'pricing.tiers.medium.description': 'Ideal for growing companies',
    'pricing.tiers.large.name': 'Large',
    'pricing.tiers.large.description': 'Great for established businesses',
    'pricing.tiers.enterprise.name': 'Enterprise',
    'pricing.tiers.enterprise.description': 'Custom pricing for large organizations',
    'pricing.tiers.enterprise.price': 'Custom',
    
    // Dashboard
    'dashboard.loading': 'Loading data...',
    'dashboard.title': 'Admin Dashboard',
    'dashboard.subtitle': 'View and manage subscriptions and payments',
    'dashboard.stats.companies': 'Companies',
    'dashboard.stats.active': 'Active Subscriptions',
    'dashboard.stats.pending': 'Pending Payment',
    'dashboard.stats.revenue': 'Monthly Revenue',
    'dashboard.companies.title': 'Companies',
    'dashboard.companies.company': 'Company',
    'dashboard.companies.status': 'Status',
    'dashboard.companies.monthly_cost': 'Monthly Cost',
    'dashboard.companies.employees': 'Employees',
    'dashboard.companies.next_payment': 'Next Payment',
    'dashboard.payments.title': 'Recent Payments',
    'dashboard.payments.order': 'Order',
    'dashboard.payments.amount': 'Amount',
    'dashboard.payments.status': 'Status',
    'dashboard.payments.date': 'Date',
    'dashboard.status.active': 'Active',
    'dashboard.status.pending_payment': 'Pending Payment',
    'dashboard.status.suspended': 'Suspended',
    'dashboard.status.cancelled': 'Cancelled',
    'dashboard.payment_status.completed': 'Completed',
    'dashboard.payment_status.processing': 'Processing',
    'dashboard.payment_status.failed': 'Failed',
    'dashboard.payment_status.pending': 'Pending',
    
    // About page
    'about.hero.title': 'About Us',
    'about.hero.subtitle': 'Solution for the problem everyone knows: forgotten birthdays',
    'about.intro.title': 'About Us',
    'about.intro.desc': 'In HR or management, there\'s always plenty to do – remembering birthdays, ordering cakes, picking them up, serving them. Even with the best intentions, things sometimes get forgotten. What should have been a joyful moment turns into stress, and a forgotten birthday can even harm morale and damage the workplace culture.',
    'about.solution.title': 'Straxkaka is the solution',
    'about.solution.desc': 'We take care of everything – you don\'t need to lift a finger. Nobody forgets anymore, and a fresh cake shows up at the office on the birthday.',
    'about.why.title': 'Why Straxkaka?',
    'about.why.no_forgotten.title': 'No forgotten birthdays',
    'about.why.no_forgotten.desc': 'We keep track of all the dates.',
    'about.why.zero_hassle.title': 'Zero hassle for HR or managers',
    'about.why.zero_hassle.desc': 'We handle the ordering, coordination, and delivery.',
    'about.why.culture.title': 'Better workplace culture',
    'about.why.culture.desc': 'Small things matter – celebrating birthdays builds unity, motivates employees, and strengthens workplace culture.',
    'about.promise.title': 'Our Promise',
    'about.promise.desc': 'We partner with trusted bakeries that use high-quality ingredients. The cakes are baked with care and delivered on time – always ready to delight.',
    'about.future.title': 'The Future',
    'about.future.desc': 'Straxkaka is more than just cake. We are building a future of workplace culture where no birthday is forgotten and no employee feels overlooked.',
    'about.team.title': 'Our Team',
    'about.team.desc': 'Hi, I\'m Bjarki, the founder of Straxkaka. I\'m 20 years old and started this company with a simple goal: to make birthdays at work easier and more meaningful. I know how stressful it can be when someone\'s birthday is forgotten, so I wanted to create a service where no one has to worry — the cake just arrives on time. I work closely with local bakeries to make sure every delivery is smooth, and I\'m dedicated to keeping the process reliable, friendly, and stress-free.',
    'about.cta.title': 'Ready to get started?',
    'about.cta.subtitle': 'Contact us and find out how Straxkaka can improve the atmosphere at your workplace.',
    'about.cta.subscribe': 'Start Subscription',
    'about.cta.contact': 'Contact Us',
    
    // Services page
    'services.hero.title': 'Our Services',
    'services.hero.subtitle': 'Everything you need to never forget employee birthdays',
    'services.cta.title': 'Ready to get started?',
    'services.cta.subtitle': 'Contact us today for a free consultation.',
    'services.cta.subscribe': 'Start Subscription',
    'services.cta.contact': 'Contact Us',
    
    // Services features
    'services.registration.feature1': 'Secure HR system connection',
    'services.registration.feature2': 'Automatic data transfer',
    'services.registration.feature3': 'GDPR compliant',
    'services.registration.feature4': '24/7 protection',
    'services.ai.desc': 'Our AI automatically orders cakes 3 days before birthdays and sends notifications to you and the employee.',
    'services.ai.feature1': 'Automatic cake ordering',
    'services.ai.feature2': 'Birthday notifications',
    'services.ai.feature3': 'Customized messages',
    'services.ai.feature4': 'Quality management',
    'services.delivery.desc': 'We work with the best bakeries in Iceland and ensure delivery to the workplace on time.',
    'services.delivery.feature1': 'Working with best bakeries',
    'services.delivery.feature2': 'Reliable delivery',
    'services.delivery.feature3': 'Multiple options',
    'services.delivery.feature4': 'Quality assurance',
    
    // Contact page
    'contact.hero.title': 'Contact Us',
    'contact.hero.subtitle': 'Contact us for a free consultation',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.company': 'Company',
    'contact.form.phone': 'Phone',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.validation.required': 'Please fill in all required fields.',
    'contact.form.success': 'Thank you for your message! We will get back to you within 24 hours.',
    'contact.form.error': 'An error occurred while sending your message. Please try again.',
    'contact.info.title': 'Information',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.q1.question': 'How much does the service cost?',
    'contact.faq.q1.answer': 'The price depends on the number of employees. Contact us for a detailed price list.',
    'contact.faq.q2.question': 'Which HR systems does StraxKaka work with?',
    'contact.faq.q2.answer': 'We work with most major HR systems in Iceland. Contact us to check if your system is available.',
    'contact.faq.q3.question': 'Which bakeries do you work with?',
    'contact.faq.q3.answer': 'We work with the best bakeries in Iceland and can offer many different options.',
    'contact.info.email.title': 'Email',
    'contact.info.email.desc': 'orders.straxkaka@outlook.com',
    'contact.info.email.note': 'we respond within 24 hours',
    'contact.info.phone.title': 'Phone',
    'contact.info.phone.desc': '+354 790 4777',
    'contact.info.phone.note': 'Mon-Fri: 09:00-17:00',
    'contact.info.orders.title': 'Orders',
    'contact.info.orders.desc': 'orders.straxkaka@outlook.com',
    'contact.info.orders.note': 'for orders and questions',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('is');
  const [isHydrated, setIsHydrated] = useState(false);

  // Handle hydration
  useEffect(() => {
    setIsHydrated(true);
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'is' || savedLanguage === 'en')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    // Use the current language state
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isHydrated }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
