'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'is' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isHydrated: boolean;
}

const translations = {
  is: {
    // Navigation
    'nav.home': 'Heim',
    'nav.about': 'Um okkur',
    'nav.services': 'Þjónusta',
    'nav.contact': 'Hafa samband',
    'nav.subscription': 'Áskrift',
    'nav.start_now': 'Byrja núna',
    
    // Homepage
    'home.hero.title': 'Afmælisdagar sem gleðja alla',
    'home.hero.subtitle': 'Með StraxKaka verður dagurinn aðeins sætari, kökurnar birtast á réttum degi og réttum tíma.',
    'home.features.title': 'Hvað gerir StraxKaka',
    'home.features.subtitle': 'Við tryggjum að allir afmælisdagar verða haldnir upp á, á réttan hátt',
    'home.how_it_works.title': 'Svo einfalt er þetta',
    'home.how_it_works.subtitle': 'Þú skráir, við sérum um allt annað',
    'home.why.title': 'Af hverju StraxKaka?',
    'home.why.subtitle': 'Lausn fyrir vandamálið sem allir þekkja',
    'home.why.stress_free.title': 'Áhyggjulaus starfsmannadeild',
    'home.why.stress_free.desc': 'Engin gleymdir afmæli',
    'home.why.morale.title': 'Byggir upp stemningu og vinnustofukúltúr',
    'home.why.morale.desc': 'Fersk kaka á afmælisdaginn',
    'home.why.reliable.title': 'Áreiðanleg afhending frá staðbundnum bakaríum',
    'home.why.reliable.desc': 'Toppstig kökur á réttum tíma',
    'home.why.time_saving.title': 'Sparar tíma og vinnu',
    'home.why.time_saving.desc': 'Við sjáum um allt ferlið',
    'home.why.quality.title': 'Gæðavottun og sérsniðin þjónusta',
    'home.why.quality.desc': 'Hvert fyrirtæki fær einstaka þjónustu',
    'home.cta.title': 'Tilbúin/n að byrja?',
    'home.cta.subtitle': 'Tilbúin/n að gera afmælisdaga áhyggjulausa? Byrjaðu áskriftina þína í dag.',
    
    // Features
    'features.registration.title': 'Skráning fer í gegnum öruggt kerfi',
    'features.registration.desc': 'Hlaða inn Excel skrá eða tengja við HR kerfið. Engin flókin uppsetning, bara skrá og gleyma.',
    'features.ai.title': 'Við pöntum kökur fyrir þig',
    'features.ai.desc': 'Við vinnum í samstarfi við frábær bakarí, og  bjóðum upp á gómsætar og fjölbreyttar kökur.',
    'features.delivery.title': 'Kökur koma á réttum degi',
    'features.delivery.desc': 'Afhending á sér stað á réttum tíma og degi, til þess að tryggja að kakan sé kominn í hadeginu.',
    
    // How it works
    'how_it_works.step1.title': '1. Skrá starfsmenn',
    'how_it_works.step1.desc': 'Hlaða inn nöfn og afmælisdaga starfsmanna. Einn skjall og þú ert komin/n.',
    'how_it_works.step2.title': '2. Við muna fyrir þig',
    'how_it_works.step2.desc': 'Kerfið muna allt og panta kökur sjálfkrafa. Engin að gleyma neitt.',
    'how_it_works.step3.title': '3. Kökurnar birtast',
    'how_it_works.step3.desc': 'Á afmælisdaginn birtast kökurnar á vinnustaðnum. Starfsmenn fagna og stemningin batnar.',
    
    // Footer
    'footer.description': 'Lausn fyrir gleymdir afmælisdaga. Við muna fyrir þig.',
    'footer.services.title': 'Þjónusta',
    'footer.services.birthday': 'Afmælisdagaskráning',
    'footer.services.ai': 'AI sjálfvirkni',
    'footer.services.ordering': 'Kökupöntun',
    'footer.services.delivery': 'Afhending',
    'footer.company.title': 'Fyrirtæki',
    'footer.company.pricing': 'Verðskrá',
    'footer.company.blog': 'Blogg',
    'footer.contact.title': 'Hafa samband',
    'footer.legal.title': 'Löglegar síður',
    'footer.legal.privacy': 'Persónuverndarstefna',
    'footer.legal.terms': 'Skilmálar',
    'footer.legal.cookies': 'Vafrakökur',
    'footer.legal.legal': 'Löglegar upplýsingar',
    'footer.copyright': '© 2025 StraxKaka. Allur réttur áskilinn. Byrjaði árið 2025.',
    
    // Common
    'common.phone': '+354 790 4777',
    'common.email': 'orders.straxkaka@outlook.com',
    
    // About page
    'about.hero.title': 'Um okkur',
    'about.hero.subtitle': 'Við trúum því að það eigi að fagna öllum',
    'about.founder.title': 'Stofnandi StraxKaka',
    'about.founder.caption': 'Founder of StraxKaka',
    'about.intro.title': 'Vandamálið',
    'about.intro.desc': 'Í starfsmannadeildina getur verið nóg að gera það þarf að muna afmælisdagsetningar, panta köku, sækja og bera hana fram. þetta getur aukið stress eða og jafnvel gleymst.',
    'about.solution.title': 'StraxKaka er lausnin',
    'about.solution.desc': 'Við sjáum um allt ferlið, þú þarft ekki að lyfta fingri. Að fagna hvort öðru hefur aldrei verið jafn létt og skemmtilegt',
    'about.why.title': 'Af hverju StraxKaka?',
    'about.why.focus.title': 'Við hjá StraxKaka leggjum áherslu á að fagna hvort öðru',
    'about.why.focus.desc': 'Við trúum því að slíkir viðburðir skipta miklu máli fyrir vinnustaðamenningu. Vinnustaðurinn er miklu meira enn bara vinna, það er staður sem við eyðum stórum hluta af lífinu okkar á. Við ættum að fagna samstarfsfolki okkar, því að góð vinnustaðamenning skiptir miklu máli.',
    'about.promise.title': 'Okkar loforð',
    'about.promise.desc': 'Við vinnum með traustum bakaríum sem nota hágæða hráefni. Kökurnar eru bakaðar af alúð og afhentar á réttum tíma – alltaf tilbúnar til að gleðja.',
    'about.future.title': 'Framtíðin',
    'about.future.desc': 'StraxKaka er meira en bara kaka. Við erum að byggja upp framtíð vinnustaðarmenningar þar sem enginn afmælisdagur er gleymdur og enginn starfsmaður vanmetinn.',
    'about.team.title': 'Teymið okkar',
    'about.team.desc': 'Hæ, ég heiti Bjarki og er stofnandi Straxköku. Ég er 20 ára og byrjaði fyrirtækið með einfalt markmið: að gera afmælisdaginn á vinnustaðnum auðveldari og skemmtilegri. Ég veit hvað það getur verið stressandi þegar afmæli gleymist, svo ég vildi búa til þjónustu þar sem enginn þarf að hafa áhyggjur – kakan mætir bara á réttum tíma. Ég vinn með góðum bakaríum til að tryggja góða þjónustu og legg áherslu á að ferlið sé áreiðanlegt, vingjarnlegt og áhyggjulaust.',
    'about.cta.title': 'Tilbúin/n að byrja?',
    'about.cta.subtitle': 'Hafðu samband við okkur og fáðu að vita hvernig StraxKaka getur bætt stemninguna á vinnustaðnum þínum.',
    'about.cta.subscribe': 'Byrja áskrift',
    'about.cta.contact': 'Hafa samband',
    
    // Subscribe page
    'subscribe.hero.title': 'Skráðu starfsmenn fyrirtækisins þíns',
    'subscribe.hero.subtitle': 'Byrjaðu að nota StraxKaka í dag og gleymdu aldrei afmælisdögum starfsmanna',
    'subscribe.company.title': 'Upplýsingar um fyrirtækið',
    'subscribe.company.name': 'Nafn fyrirtækis',
    'subscribe.company.contact_name': 'Nafn tengiliðs',
    'subscribe.company.email': 'Netfang',
    'subscribe.company.phone': 'Símanúmer',
    'subscribe.company.address': 'Heimilisfang fyrir afhendingu',
    'subscribe.employees.title': 'Starfsmenn',
    'subscribe.employees.add': 'Bæta við starfsmanni',
    'subscribe.employees.employee': 'Starfsmaður',
    'subscribe.employees.remove': 'Fjarlægja',
    'subscribe.employees.name': 'Nafn',
    'subscribe.employees.birthday': 'Afmælisdagur',
    'subscribe.employees.cake_type': 'Tegund köku',
    'subscribe.employees.dietary': 'Matarheftir',
    'subscribe.employees.notes': 'Sérstakar athugasemdir',
    'subscribe.employees.file_upload': 'Hlaða upp skrá',
    'subscribe.submit': 'Skrá fyrirtæki',
    'subscribe.submitting': 'Skrái...',
    'subscribe.success.title': 'Takk fyrir skráninguna!',
    'subscribe.success.message': 'Við höfum móttekið upplýsingarnar um starfsmenn fyrirtækisins þíns. Við höfum samband innan 24 klukkustunda til að ræða næstu skref.',
    'subscribe.success.back_home': 'Til baka á heimasíðuna',
    'subscribe.success.view_submissions': 'Skoða skráningar (fyrir stjórnendur)',
    
    // Admin page
    'admin.loading': 'Hleð gögnum...',
    'admin.title': 'Stjórnendadashboard',
    'admin.subtitle': 'Skoða og stjórna skráningum fyrirtækja og starfsmanna',
    'admin.stats.companies': 'Fyrirtæki',
    'admin.stats.employees': 'Starfsmenn',
    'admin.stats.upcoming': 'Kemur afmæli næstu 30 daga',
    'admin.stats.average': 'Meðaltal starfsmanna',
    'admin.stats.active_companies': 'Aktív fyrirtæki',
    'admin.stats.active_employees': 'Aktívir starfsmenn',
    'admin.stats.upcoming_week': 'Kemur afmæli næstu 7 daga',
    'admin.stats.deliveries_today': 'Afhendingar í dag',
    'admin.stats.mrr': 'Mánaðarleg tekjur',
    'admin.satisfaction.title': 'Viðskiptavinastuðningur',
    'admin.satisfaction.no_ratings': 'Engin viðskiptavinastuðningur skráður enn',
    'admin.communication.title': 'Nýleg samskipti',
    'admin.communication.no_activity': 'Engin samskipti skráð enn',
    'admin.upcoming.title': 'Kemur afmæli næstu 30 daga',
    'admin.upcoming.cake_type': 'Tegund köku',
    'admin.upcoming.today': 'Í dag!',
    'admin.upcoming.days': 'daga',
    'admin.search.title': 'Leita',
    'admin.search.company': 'Fyrirtækið',
    'admin.search.all': 'Allir',
    'admin.export': 'Flytja út CSV',
    'admin.submissions.title': 'Skráningar',
    'admin.submissions.empty': 'Engar skráningar fundust',
    'admin.table.company': 'Fyrirtækið',
    'admin.table.contact': 'Tengiliður',
    'admin.table.employees': 'Starfsmenn',
    'admin.table.date': 'Dagsetning',
    'admin.table.actions': 'Aðgerðir',
    'admin.table.employees_count': 'starfsmenn',
    'admin.table.view': 'Skoða',
    'admin.table.delivered': 'Afhent',
    'admin.modal.company_info': 'Upplýsingar um fyrirtækið',
    'admin.modal.contact': 'Tengiliður',
    'admin.modal.phone': 'Sími',
    'admin.modal.address': 'Heimilisfang',
    'admin.modal.employees': 'Starfsmenn',
    'admin.modal.birthday': 'Afmælisdagur',
    'admin.modal.cake_type': 'Tegund köku',
    'admin.modal.dietary': 'Matarheftir',
    'admin.modal.notes': 'Athugasemdir',
    
    // CSV Upload
    'csv.upload.title': 'Hlaða upp CSV skrá',
    'csv.upload.subtitle': 'Hlaða upp CSV skrá með starfsmönnum fyrir fljótlega skráningu',
    'csv.upload.download_template': 'Sækja sniðmát',
    'csv.upload.processing': 'Vinnur...',
    'csv.upload.select_file': 'Velja CSV skrá',
    'csv.preview.title': 'Forskoðun CSV gögn',
    'csv.preview.confirm': 'Staðfesta',
    'csv.preview.cancel': 'Hætta við',
    'csv.preview.valid': 'Gildir',
    'csv.preview.invalid': 'Ógildir',
    'csv.preview.row': 'Röð',
    'csv.preview.name': 'Nafn',
    'csv.preview.birthday': 'Afmælisdagur',
    'csv.preview.cake_type': 'Tegund köku',
    'csv.preview.status': 'Staða',
    'csv.success.employees_added': 'starfsmenn bætt við',
    'csv.errors.insufficient_columns': 'Ófullnægjandi dálkar',
    'csv.errors.name_required': 'Nafn er nauðsynlegt',
    'csv.errors.birthday_required': 'Afmælisdagur er nauðsynlegur',
    'csv.errors.invalid_birthday': 'Ógildur afmælisdagur',
    'csv.errors.cake_type_required': 'Tegund köku er nauðsynleg',
    'csv.errors.invalid_file_type': 'Ógild skráartegund. Vinsamlegast veldu CSV skrá.',
    'csv.errors.parse_error': 'Villa við að þýða CSV skrá',
    'csv.errors.read_error': 'Villa við að lesa skrá',
    'csv.errors.no_valid_rows': 'Engar gildar raðir fundust',
    
    // Enhanced File Upload
    'file.upload.title': 'Hlaða upp skrá með starfsmönnum',
    'file.upload.subtitle': 'Stuðningur við CSV, Excel (.xlsx) og Google Sheets',
    'file.upload.download_csv': 'Sækja CSV sniðmát',
    'file.upload.download_excel': 'Sækja Excel sniðmát',
    'file.upload.open_google_sheets': 'Opna Google Sheets',
    'file.upload.processing': 'Vinnur...',
    'file.upload.select_file': 'Velja skrá',
    'file.upload.supported_formats': 'CSV, Excel (.xlsx, .xls)',
    'file.preview.title': 'Forskoðun skrárgögn',
    'file.preview.confirm': 'Staðfesta',
    'file.preview.cancel': 'Hætta við',
    'file.preview.valid': 'Gildir',
    'file.preview.invalid': 'Ógildir',
    'file.preview.row': 'Röð',
    'file.preview.name': 'Nafn',
    'file.preview.birthday': 'Afmælisdagur',
    'file.preview.cake_type': 'Tegund köku',
    'file.preview.status': 'Staða',
    'file.success.employees_added': 'starfsmenn bætt við',
    'file.errors.insufficient_columns': 'Ófullnægjandi dálkar',
    'file.errors.name_required': 'Nafn er nauðsynlegt',
    'file.errors.birthday_required': 'Afmælisdagur er nauðsynlegur',
    'file.errors.invalid_birthday': 'Ógildur afmælisdagur',
    'file.errors.cake_type_required': 'Tegund köku er nauðsynleg',
    'file.errors.invalid_file_type': 'Ógild skráartegund. Vinsamlegast veldu CSV eða Excel skrá.',
    'file.errors.csv_parse_error': 'Villa við að þýða CSV skrá',
    'file.errors.excel_parse_error': 'Villa við að þýða Excel skrá',
    'file.errors.read_error': 'Villa við að lesa skrá',
    'file.errors.no_valid_rows': 'Engar gildar raðir fundust',
    'file.errors.unknown_error': 'Óþekkt villa',
    'file.errors.excel_import_error': 'Villa við að hlaða inn Excel bókunni',
    'file.errors.download_error': 'Villa við að sækja sniðmát',
    
    // Subscription System
    'subscription.loading': 'Hleð gögnum...',
    'subscription.steps.company': 'Upplýsingar um fyrirtækið',
    'subscription.steps.employees': 'Starfsmenn',
    'subscription.steps.subscription': 'Áskrift',
    'subscription.steps.payment': 'Greiðsla',
    'subscription.company.title': 'Upplýsingar um fyrirtækið',
    'subscription.company.name': 'Nafn fyrirtækis',
    'subscription.company.contact_name': 'Nafn tengiliðs',
    'subscription.company.email': 'Netfang',
    'subscription.company.phone': 'Símanúmer',
    'subscription.company.address': 'Heimilisfang fyrir afhendingu',
    'subscription.employees.title': 'Starfsmenn',
    'subscription.employees.file_upload': 'Hlaða upp skrá',
    'subscription.employees.add': 'Bæta við starfsmanni',
    'subscription.employees.employee': 'Starfsmaður',
    'subscription.employees.remove': 'Fjarlægja',
    'subscription.employees.name': 'Nafn',
    'subscription.employees.birthday': 'Afmælisdagur',
    'subscription.employees.birthday_hint': 'Smelltu á reitinn til að velja dagsetningu',
    'subscription.employees.cake_type': 'Tegund köku',
    'subscription.employees.cake_size': 'Stærð köku',
    'subscription.employees.dietary': 'Matarheftir',
    'subscription.employees.notes': 'Sérstakar athugasemdir',
    'subscription.navigation.back': 'Til baka',
    'subscription.navigation.next': 'Áfram',
    'subscription.navigation.submit': 'Skrá áskrift',
    'subscription.navigation.submitting': 'Skrái...',
    'subscription.success.title': 'Takk fyrir skráninguna!',
    'subscription.success.message': 'Við höfum móttekið áskriftarbeiðni fyrir fyrirtækið þitt. Við höfum samband innan 24 klukkustunda til að ræða greiðslu og næstu skref.',
    'subscription.success.back_home': 'Til baka á heimasíðuna',
    'subscription.success.view_subscriptions': 'Skoða áskriftir (fyrir stjórnendur)',
    'subscription.success.employees_added': 'starfsmenn bætt við',
    'subscription.errors.company_name_required': 'Nafn fyrirtækis er nauðsynlegt',
    'subscription.errors.invalid_email': 'Ógilt netfang',
    'subscription.errors.invalid_phone': 'Ógilt símanúmer',
    'subscription.errors.address_required': 'Heimilisfang fyrir afhendingu er nauðsynlegt',
    'subscription.errors.no_employees': 'Að minnsta kosti einn starfsmaður er nauðsynlegur',
    'subscription.errors.employee_name_required': 'Nafn starfsmanns er nauðsynlegt',
    'subscription.errors.birthday_required': 'Afmælisdagur er nauðsynlegur',
    'subscription.errors.invalid_birthday': 'Ógildur afmælisdagur',
    'subscription.errors.cake_type_required': 'Tegund köku er nauðsynleg',
    'subscription.errors.tier_required': 'Vinsamlegast veldu áskriftarstig',
    'subscription.errors.submission_failed': 'Villa við skráningu. Vinsamlegast reyndu aftur.',
    
    // Cake Types
    'cake.rosakaka_ljos_sukkuladi': 'Rósakaka ljóst sukkulaði',
    'cake.rosakaka_dokkt_sukkuladi': 'Rósakaka dökkt súkkulaði',
    'cake.skuffukaka_bakka': 'Skúffukaka á bakka',
    'cake.jardaberja': 'Jarðaberja',
    'cake.sitronuost': 'Sitronuost',
    'cake.biscoff': 'Biscoff',
    'cake.daim': 'Daim',
    'cake.tiramisu': 'Tiramisu',
    'cake.sukkuladi_karamellukremi': 'Súkkulaði með karamellukremi',
    'cake.sukkuladi_sukkuladikremi': 'Súkkulaði með súkkulaðikremi',
    
    // Payment step
    'subscription.payment.title': 'Greiðsla',
    'subscription.payment.summary': 'Pöntunaryfirlit',
    'subscription.payment.company': 'Fyrirtækið',
    'subscription.payment.tier': 'Áskriftarstig',
    'subscription.payment.employee_count': 'Fjöldi starfsmanna',
    'subscription.payment.monthly_cost': 'Mánaðargjald',
    'subscription.payment.method': 'Greiðslumáti',
    'subscription.payment.aur.title': 'AUR greiðsla',
    'subscription.payment.aur.description': 'Greiðsla verður send á símanúmerið þitt: {phone}',
    'subscription.payment.aur.sms_note': 'Þú færð SMS með hlekk til að ljúka greiðslunni',
    'subscription.payment.bank_transfer.title': 'Bankagreiðsla',
    'subscription.payment.bank_transfer.description': 'Fáðu bankaupplýsingar og einstakt viðmiðunarnúmer fyrir greiðslu',
    'subscription.payment.bank_transfer.activation_note': 'Áskriftin verður virkjuð þegar greiðslan er staðfest',
    'subscription.payment.bank_transfer.success_message': 'Bankaupplýsingar hefur verið búið til. Vinsamlegast ljúktu bankagreiðslunni til að virkja áskriftina.',
    'subscription.payment.bank_transfer.instructions': 'Bankagreiðsluupplýsingar',
    'subscription.payment.bank_transfer.bank_name': 'Banki',
    'subscription.payment.bank_transfer.account_number': 'Reikningsnúmer',
    'subscription.payment.bank_transfer.reference': 'Viðmiðunarnúmer',
    'subscription.payment.bank_transfer.amount': 'Upphæð',
    'subscription.payment.bank_transfer.note': 'Vinsamlegast ljúktu bankagreiðslunni. Áskriftin verður virkjuð þegar greiðslan er staðfest.',
    'subscription.payment.bank_transfer.success_title': 'Bankaupplýsingar búnar til!',
    'subscription.payment.terms': 'Ég samþykki að greiða mánaðarlega greiðslu fyrir StraxKaka þjónustuna og skil að hægt er að hætta hvenær sem er.',
    'subscription.payment.success_message': 'Greiðslubeiðni hefur verið send á símanúmerið þitt. Vinsamlegast ljúktu greiðslunni til að virkja áskriftina.',
    'subscription.payment.success_title': 'Greiðslubeiðni send!',
    'subscription.payment.phone_number': 'Símanúmer',
    'subscription.navigation.processing': 'Greiði...',
    'subscription.navigation.pay_now': 'Greiða núna',
    'subscription.hero.title': 'Byrjaðu áskrift á StraxKaka',
    'subscription.hero.subtitle': 'Aldrei gleymdu afmæli aftur - við sjáum um það fyrir þig',
    'subscription.features.automatic': 'Sjálfvirk áminning',
    'subscription.features.automatic_desc': 'Við muna öll afmæli fyrir þig',
    'subscription.features.delivery': 'Áfhending',
    'subscription.features.delivery_desc': 'Kökur koma beint á vinnustaðinn',
    'subscription.features.simple': 'Einfalt',
    'subscription.features.simple_desc': 'Engin flækja - bara fínn þjónusta',
    
    // Pricing
    'pricing.title': 'Verðskrá',
    'pricing.subtitle': 'Mánaðarleg áskrift + kökugjöld',
    'pricing.simple.title': 'Einfalt verð',
    'pricing.simple.subtitle': 'Veldu réttan áætlun fyrir stærð fyrirtækisins þíns',
    'pricing.little.title': 'Lítil fyrirtæki',
    'pricing.little.price': '15.000 ISK',
    'pricing.little.billing': 'á mánuði + kökugjöld',
    'pricing.little.description': 'Hentar fyrir 1-25 starfsmenn',
    'pricing.medium.title': 'Meðalstór fyrirtæki',
    'pricing.medium.description': 'Hentar fyrir 26-50 starfsmenn',
    'pricing.large.title': 'Stór fyrirtæki',
    'pricing.large.description': 'Hentar fyrir 51+ starfsmenn',
    'pricing.little_company': 'Lítil fyrirtæki (1-25 starfsmenn)',
    'pricing.little_company_price': '15.000 ISK á mánuði + kökugjöld',
    'pricing.contact_for_pricing': 'Hafa samband',
    'pricing.for_pricing': 'fyrir verð',
    'pricing.recommended': 'Mælt með',
    'pricing.per_month': 'á mánuði',
    'pricing.employees': 'starfsmenn',
    'pricing.suitable': 'Hentar fyrir fyrirtækið þitt',
    'pricing.not_suitable': 'Ekki hentar fyrir fyrirtækið þitt',
    'pricing.selected': 'Valið',
    'pricing.select': 'Velja',
    'pricing.for_your_company': 'Fyrir fyrirtækið þitt',
    'pricing.for': 'Fyrir',
    'pricing.disclaimer': 'Allar verðir eru með 24% VSK. Engin uppsetningargjald. Hægt að hætta hvenær sem er.',
    'pricing.tiers.small.name': 'Lítill',
    'pricing.tiers.small.description': 'Hentar fyrir litla teymi',
    'pricing.tiers.medium.name': 'Meðalstór',
    'pricing.tiers.medium.description': 'Hentar fyrir vaxandi fyrirtæki',
    'pricing.tiers.large.name': 'Stór',
    'pricing.tiers.large.description': 'Hentar fyrir stofnuð fyrirtæki',
    'pricing.tiers.enterprise.name': 'Fyrirtæki',
    'pricing.tiers.enterprise.description': 'Sérsniðið verð fyrir stórar stofnanir',
    'pricing.tiers.enterprise.price': 'Sérsniðið',
    
    // Additional pricing for services page
    'pricing.small.title': 'Lítill',
    'pricing.small.price': 'Sérsniðið',
    'pricing.small.description': 'Fyrir fyrir 50 starfsmenn',
    'pricing.small.billing': 'Greiðist fyrir hvern afmælisdag',
    'pricing.starter.title': 'Meðalstór',
    'pricing.starter.price': '60.000 ISK',
    'pricing.starter.description': 'Fyrir 50+ starfsmenn',
    'pricing.starter.billing': 'Greiðist fyrir hvern afmælisdag (~12.600 ISK)',
    'pricing.professional.title': 'Stór',
    'pricing.professional.price': '120.000 ISK',
    'pricing.professional.description': 'Fyrir 100+ starfsmenn',
    'pricing.professional.billing': 'Greiðist fyrir hvern afmælisdag',
    'pricing.business.title': 'Fyrirtæki',
    'pricing.business.price': 'Sérsniðið',
    'pricing.business.description': 'Fyrir 200+ starfsmenn',
    'pricing.business.billing': 'Greiðist fyrir hvern afmælisdag (~12.600 ISK)',
    'pricing.enterprise.title': 'Enterprise',
    'pricing.enterprise.price': 'Custom',
    'pricing.enterprise.description': 'For 200+ employees',
    'pricing.enterprise.billing': 'Billed per birthday (~12,600 ISK each)',
    
    // Dashboard
    'dashboard.loading': 'Hleð gögnum...',
    'dashboard.title': 'Stjórnendadashboard',
    'dashboard.subtitle': 'Skoða og stjórna áskriftum og greiðslum',
    'dashboard.stats.companies': 'Fyrirtæki',
    'dashboard.stats.active': 'Aktívar áskriftir',
    'dashboard.stats.pending': 'Bíður greiðslu',
    'dashboard.stats.revenue': 'Mánaðartekjur',
    'dashboard.companies.title': 'Fyrirtæki',
    'dashboard.companies.company': 'Fyrirtæki',
    'dashboard.companies.status': 'Staða',
    'dashboard.companies.monthly_cost': 'Mánaðargjald',
    'dashboard.companies.employees': 'Starfsmenn',
    'dashboard.companies.next_payment': 'Næsta greiðsla',
    'dashboard.payments.title': 'Nýlegar greiðslur',
    'dashboard.payments.order': 'Pöntun',
    'dashboard.payments.amount': 'Upphæð',
    'dashboard.payments.status': 'Staða',
    'dashboard.payments.date': 'Dagsetning',
    'dashboard.status.active': 'Virk',
    'dashboard.status.pending_payment': 'Bíður greiðslu',
    'dashboard.status.suspended': 'Í bið',
    'dashboard.status.cancelled': 'Hætt',
    'dashboard.payment_status.completed': 'Lokið',
    'dashboard.payment_status.processing': 'Vinnur',
    'dashboard.payment_status.failed': 'Mistókst',
    'dashboard.payment_status.pending': 'Bíður',
    
    // Services page
    'services.hero.title': 'Þjónustan okkar',
    'services.hero.subtitle': 'Við leysum vandamálið sem allir þekkja: gleymdir afmælisdagum sem skaða samstöðu og stemningu',
    'services.process.title': 'Hvernig virkar það?',
    'services.process.subtitle': 'Einfalt ferli í 4 skrefum',
    'services.detailed.title': 'Þjónustan okkar',
    'services.detailed.subtitle': 'Allt sem þú þarft fyrir fullkomna afmælisstund',
    'services.benefits.title': 'Kostir StraxKaka',
    'services.benefits.subtitle': 'Hvers vegna velja fyrirtæki StraxKaka?',
    'services.cta.title': 'Tilbúin/n að byrja?',
    'services.cta.subtitle': 'Hafðu samband við okkur og fáðu að vita hvernig StraxKaka getur bætt stemninguna á vinnustaðnum þínum.',
    'services.cta.subscribe': 'Byrja áskrift',
    'services.cta.contact': 'Hafa samband',
    
    // Services features
    'services.registration.feature1': 'Skráning í öruggu kerfi',
    'services.registration.feature2': 'Hlaða inn Excel skrá',
    'services.registration.feature3': 'Engin flókin uppsetning',
    'services.registration.feature4': 'Örugg gagnavörn',
    'services.ai.desc': 'Kerfið panta kökur fyrir þig. Kökurnar koma með engum áhyggjum á sérstakan daginn, með tilkynningum og öllu.',
    'services.ai.feature1': 'Kerfið panta kökur fyrir þig',
    'services.ai.feature2': 'Kökurnar koma með engum áhyggjum',
    'services.ai.feature3': 'Tilkynningar og allt',
    'services.ai.feature4': 'Á sérstakan daginn',
    'services.delivery.desc': 'Við vinnum með frábærum bakaríum sem bjóða upp á toppstig kökur og tryggja afhendingu á réttum tíma, með fjölbreytilegum valkostum.',
    'services.delivery.feature1': 'Frábær kökubúðir',
    'services.delivery.feature2': 'Toppstig kökur',
    'services.delivery.feature3': 'Fjölbreytilegir valkostir',
    'services.delivery.feature4': 'Áreiðanleg afhending',
    'services.cakes.title': 'Kökur sem við bjóðum upp á',
    'services.cakes.subtitle': 'Flestir kökur eru af sömu stærð - fullkominn fyrir afmælisdaga',
    'services.cakes.delivery_included': 'Afhending innifalin',
    'services.cakes.rose_light': 'Rósakaka ljóst sukkulaði',
    'services.cakes.rose_dark': 'Rósakaka dökkt súkkulaði',
    'services.cakes.skuffu': 'Skúffukaka á bakka',
    'services.cakes.strawberry': 'Jarðaberja',
    'services.cakes.lemon_cheese': 'Sitronuost',
    'services.cakes.biscoff': 'Biscoff',
    'services.cakes.daim': 'Daim',
    'services.cakes.tiramisu': 'Tiramisu',
    'services.cakes.chocolate_caramel': 'Súkkulaði með karamellukremi',
    'services.cakes.chocolate_cream': 'Súkkulaði með súkkulaðikremi',
    
    // Contact page
    'contact.hero.title': 'Hafðu samband',
    'contact.hero.subtitle': 'Hafðu samband við okkur og fáðu að vita hvernig StraxKaka getur bætt stemninguna á vinnustaðnum þínum',
    'contact.info.subtitle': 'Einfalt að ná til okkur',
    'contact.info.email.desc': 'Sendu okkur tölvupóst fyrir allar fyrirspurnir',
    'contact.info.phone.desc': 'Hringdu í okkur á virkum dögum 9:00-17:00',
    'contact.support.email.title': 'Tölvupóstur',
    'contact.support.email.desc': 'Sendu okkur tölvupóst fyrir almennar fyrirspurnir, aðstoð eða viðskiptaspurningar',
    'contact.support.email.action': 'Senda tölvupóst',
    'contact.support.phone.title': 'Sími',
    'contact.support.phone.desc': 'Hringdu í okkur fyrir tafarlausa aðstoð eða brýn mál',
    'contact.support.phone.action': 'Hringja núna',
    'contact.support.hours.title': 'Opnunartími',
    'contact.support.hours.desc': 'Mánudagur - Föstudagur: 9:00 - 17:00 (GMT)',
    'contact.why.title': 'Af hverju StraxKaka?',
    'contact.why.subtitle': 'Við erum hér til að hjálpa þér að bæta vinnustofuþjónustuna',
    'contact.why.fast.title': 'Fljótur svörun',
    'contact.why.fast.desc': 'Við svörum öllum fyrirspurnum innan 24 klukkustunda',
    'contact.why.reliable.title': 'Áreiðanleg þjónusta',
    'contact.why.reliable.desc': 'Engin gleymdir afmæli með okkar kerfi',
    'contact.why.personal.title': 'Persónuleg þjónusta',
    'contact.why.personal.desc': 'Við þjónustum hvert fyrirtæki með sérstökum hætti',
    
    // Blog
    'blog.article.title': 'Sætt leyndarmál að hamingjusamari vinnustað: Aldrei gleyma afmælum aftur',
    'blog.article.excerpt': 'Vinnustaðir eru meira en skrifstofur þar sem verkefni eru unnin – þeir eru samfélög þar sem fólk eyðir stórum hluta lífs síns. Í þessum rýmum skiptir máli að fólk líði vel, finni sig metið og upplifi þakklæti. Ein af einföldustu en áhrifaríkustu leiðunum til að skapa þessa menningu? Að fagna afmælum.',
    'blog.article.read_more': 'Lesa grein',
    'blog.title': 'Blogg',
    'blog.section.title': 'Grein',
    'blog.section.subtitle': 'Hvernig fögnuður innan vinnustaðs getur breytt stemninguni',
    'blog.hero.title': 'Sætt leyndarmál að hamingjusamari vinnustað: Aldrei gleyma afmælum aftur',
    'blog.hero.subtitle': 'Hvernig fögnuður innan vinnustaðs getur breytt stemninguni',
    'blog.content.intro': 'Vinnustaðir eru meira en skrifstofur þar sem verkefni eru unnin – þeir eru samfélög þar sem fólk eyðir stórum hluta lífs síns. Í þessum rýmum skiptir máli að fólk líði vel, finni sig metið og upplifi þakklæti. Ein af einföldustu en áhrifaríkustu leiðunum til að skapa þessa menningu? Að fagna afmælum.',
    'blog.content.why_matter.title': 'Af hverju fagnað skiptir máli',
    'blog.content.why_matter.desc': 'Það virðist smátt, en það að muna afmæli sendir sterkt skilaboð: \'Þú skiptir máli hér.\' Regluleg fagnaðshátíð styrkir samstöðu og samstarf á milli starfsmanna og eykur tilfinningu um samhug. Þegar fólk finnur sig metið eykst áhugi, samvinna og framleiðni. Með öðrum orðum, smá gjörningur getur haft stór áhrif á vinnustaðinn.',
    'blog.content.cost_forgetting.title': 'Afleiðingar þess að gleyma',
    'blog.content.cost_forgetting.desc': 'Aftur á móti, þegar afmæli gleymist, getur það valdið streitu, misskilningi og jafnvel pirringi, sem smátt og smátt skemmir starfsanda og vinnumenningu. Starfsmenn í mannauði reyna að muna öll afmæli, en í uppteknum vinnustofum með mörgum starfsmönnum er auðvelt að gleyma einhverjum. Jafnvel þegar einhver man, getur ferlið við að panta, samræma og afhenda köku verið tímafrekt og stressandi.',
    'blog.content.enter_straxkaka.title': 'Hér kemur StraxKaka inn',
    'blog.content.enter_straxkaka.desc': 'Þar kemur StraxKaka til sögunnar. Þjónustan okkar tryggir að enginn afmælisdagur fari framhjá og léttir álag af mannauði og stjórnendum. Með sjálfvirkum áminningum og einfaldri kökuafhendingu sjáum við til þess að starfsmenn finni sig metna og fagnað—án þess að nokkur þurfi að lyfta fingri.',
    'blog.content.investment.intro': 'Með því að fjárfesta í StraxKaka fjárfestir fyrirtækið í:',
    'blog.content.investment.happiness': 'Hamingju starfsmanna: Litlir gjörningar eins og að muna afmæli auka starfsanda.',
    'blog.content.investment.cohesion': 'Samstöðu í teymi: Að deila fagnaðshátíðum styrkir tengsl og samstarf.',
    'blog.content.investment.productivity': 'Framleiðni: Hamingjusamir starfsmenn eru hvattari og skila betri árangri.',
    'blog.content.investment.efficiency': 'Tíma og álags minnkun mannauðs: Sjálfvirkni sparar tíma og dregur úr álagi.',
    'blog.content.more_than_cake.title': 'Meira en bara köka',
    'blog.content.more_than_cake.desc': 'Þetta snýst ekki bara um kökuna—heldur um að byggja menningu þar sem fólk finnur sig metið. Hvert afmæli er áminning um að hver starfsmaður skiptir máli, sem skapar vinnustað þar sem fólk hlakkar til að mæta, vinnur betur saman og byggir sterkari tengsl.',
    'blog.content.conclusion.main': 'StraxKaka gleymir ekki afmælum. Hún sætir menninguna og breytir venjulegum vinnudögum í stundir tengsla, gleði og viðurkenningar.',
    'blog.content.conclusion.cta': 'Fjárfestu í hamingju teymisins þíns. Fjárfestu í StraxKaka. Því þegar enginn afmælisdagur gleymist, verður vinnumenningin aðeins sætari á hverjum degi.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.subscription': 'Subscription',
    'nav.start_now': 'Get Started',
    
    // Homepage
    'home.hero.title': 'Never Forget Employee Birthdays Again',
    'home.hero.subtitle': 'Our system orders cakes for company employees so no one forgets birthdays. StraxKaka handles everything - from registration to delivery.',
    'home.features.title': 'What does StraxKaka do?',
    'home.features.subtitle': 'We automate the birthday cake process for your company',
    'home.how_it_works.title': 'How does it work?',
    'home.how_it_works.subtitle': 'Simple process in 3 steps',
    'home.why.title': 'Why StraxKaka?',
    'home.why.subtitle': 'Solution for the problem everyone knows',
    'home.why.stress_free.title': 'Stress-free HR',
    'home.why.stress_free.desc': 'No forgotten birthdays',
    'home.why.morale.title': 'Builds morale & workplace culture',
    'home.why.morale.desc': 'Fresh cake on the birthday',
    'home.why.reliable.title': 'Reliable deliveries from local bakeries',
    'home.why.reliable.desc': 'Top-notch cakes on time',
    'home.why.time_saving.title': 'Saves time and effort',
    'home.why.time_saving.desc': 'We handle the entire process',
    'home.why.quality.title': 'Quality assurance & personalized service',
    'home.why.quality.desc': 'Each company gets unique service',
    'home.cta.title': 'Ready to get started?',
    'home.cta.subtitle': 'Ready to make birthdays stress-free? Start your subscription today.',
    
    // Features
    'features.registration.title': 'Birthday Registration',
    'features.registration.desc': 'We connect to your HR system and transfer all birthday information to our secure system.',
    'features.ai.title': 'Our System',
    'features.ai.desc': 'Our system handles ordering the right cake for the right employee at the right time.',
    'features.delivery.title': 'Delivery',
    'features.delivery.desc': 'Cakes are delivered directly to the workplace on the birthday.',
    
    // How it works
    'how_it_works.step1.title': '1. Connect HR System',
    'how_it_works.step1.desc': 'We connect to your HR system and transfer birthday information.',
    'how_it_works.step2.title': '2. Our System Orders Cakes',
    'how_it_works.step2.desc': 'Our system automatically orders cakes for birthdays.',
    'how_it_works.step3.title': '3. Delivery',
    'how_it_works.step3.desc': 'Cakes are delivered to the workplace on the birthday.',
    
    // Footer
    'footer.description': 'Our system for birthday cakes for Icelandic companies.',
    'footer.services.title': 'Services',
    'footer.services.birthday': 'Birthday Registration',
    'footer.services.ai': 'Our System',
    'footer.services.ordering': 'Cake Ordering',
    'footer.services.delivery': 'Delivery',
    'footer.company.title': 'Company',
    'footer.company.pricing': 'Pricing',
    'footer.company.blog': 'Blog',
    'footer.contact.title': 'Contact',
    'footer.legal.title': 'Legal Pages',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms of Service',
    'footer.legal.cookies': 'Cookie Policy',
    'footer.legal.legal': 'Legal Information',
    'footer.copyright': '© 2025 StraxKaka. All rights reserved. Started in 2025.',
    
    // Common
    'common.phone': '+354 790 4777',
    'common.email': 'orders.straxkaka@outlook.com',
    
    
    // Subscribe page
    'subscribe.hero.title': 'Register Your Company Employees',
    'subscribe.hero.subtitle': 'Start using StraxKaka today and never forget employee birthdays',
    'subscribe.company.title': 'Company Information',
    'subscribe.company.name': 'Company Name',
    'subscribe.company.contact_name': 'Contact Person Name',
    'subscribe.company.email': 'Email',
    'subscribe.company.phone': 'Phone Number',
    'subscribe.company.address': 'Delivery Address',
    'subscribe.employees.title': 'Employees',
    'subscribe.employees.add': 'Add Employee',
    'subscribe.employees.employee': 'Employee',
    'subscribe.employees.remove': 'Remove',
    'subscribe.employees.name': 'Name',
    'subscribe.employees.birthday': 'Birthday',
    'subscribe.employees.cake_type': 'Cake Type',
    'subscribe.employees.dietary': 'Dietary Restrictions',
    'subscribe.employees.notes': 'Special Notes',
    'subscribe.employees.file_upload': 'Upload File',
    'subscribe.submit': 'Register Company',
    'subscribe.submitting': 'Submitting...',
    'subscribe.success.title': 'Thank you for registering!',
    'subscribe.success.message': 'We have received the information about your company employees. We will contact you within 24 hours to discuss next steps.',
    'subscribe.success.back_home': 'Back to Homepage',
    'subscribe.success.view_submissions': 'View Submissions (Admin)',
    
    // Admin page
    'admin.loading': 'Loading data...',
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'View and manage company and employee registrations',
    'admin.stats.companies': 'Companies',
    'admin.stats.employees': 'Employees',
    'admin.stats.upcoming': 'Birthdays in next 30 days',
    'admin.stats.average': 'Average employees',
    'admin.stats.active_companies': 'Active Companies',
    'admin.stats.active_employees': 'Active Employees',
    'admin.stats.upcoming_week': 'Upcoming Birthdays (7 days)',
    'admin.stats.deliveries_today': 'Deliveries Today',
    'admin.stats.mrr': 'Monthly Revenue',
    'admin.satisfaction.title': 'Customer Satisfaction',
    'admin.satisfaction.no_ratings': 'No customer ratings recorded yet',
    'admin.communication.title': 'Recent Communication',
    'admin.communication.no_activity': 'No communication activity recorded yet',
    'admin.upcoming.title': 'Birthdays in next 30 days',
    'admin.upcoming.cake_type': 'Cake Type',
    'admin.upcoming.today': 'Today!',
    'admin.upcoming.days': 'days',
    'admin.search.title': 'Search',
    'admin.search.company': 'Company',
    'admin.search.all': 'All',
    'admin.export': 'Export CSV',
    'admin.submissions.title': 'Submissions',
    'admin.submissions.empty': 'No submissions found',
    'admin.table.company': 'Company',
    'admin.table.contact': 'Contact',
    'admin.table.employees': 'Employees',
    'admin.table.date': 'Date',
    'admin.table.actions': 'Actions',
    'admin.table.employees_count': 'employees',
    'admin.table.view': 'View',
    'admin.table.delivered': 'Delivered',
    'admin.modal.company_info': 'Company Information',
    'admin.modal.contact': 'Contact',
    'admin.modal.phone': 'Phone',
    'admin.modal.address': 'Address',
    'admin.modal.employees': 'Employees',
    'admin.modal.birthday': 'Birthday',
    'admin.modal.cake_type': 'Cake Type',
    'admin.modal.dietary': 'Dietary Restrictions',
    'admin.modal.notes': 'Notes',
    
    // CSV Upload
    'csv.upload.title': 'Upload CSV File',
    'csv.upload.subtitle': 'Upload a CSV file with employees for quick registration',
    'csv.upload.download_template': 'Download Template',
    'csv.upload.processing': 'Processing...',
    'csv.upload.select_file': 'Select CSV File',
    'csv.preview.title': 'CSV Data Preview',
    'csv.preview.confirm': 'Confirm',
    'csv.preview.cancel': 'Cancel',
    'csv.preview.valid': 'Valid',
    'csv.preview.invalid': 'Invalid',
    'csv.preview.row': 'Row',
    'csv.preview.name': 'Name',
    'csv.preview.birthday': 'Birthday',
    'csv.preview.cake_type': 'Cake Type',
    'csv.preview.status': 'Status',
    'csv.success.employees_added': 'employees added',
    'csv.errors.insufficient_columns': 'Insufficient columns',
    'csv.errors.name_required': 'Name is required',
    'csv.errors.birthday_required': 'Birthday is required',
    'csv.errors.invalid_birthday': 'Invalid birthday',
    'csv.errors.cake_type_required': 'Cake type is required',
    'csv.errors.invalid_file_type': 'Invalid file type. Please select a CSV file.',
    'csv.errors.parse_error': 'Error parsing CSV file',
    'csv.errors.read_error': 'Error reading file',
    'csv.errors.no_valid_rows': 'No valid rows found',
    
    // Enhanced File Upload
    'file.upload.title': 'Upload File with Employees',
    'file.upload.subtitle': 'Support for CSV, Excel (.xlsx) and Google Sheets',
    'file.upload.download_csv': 'Download CSV Template',
    'file.upload.download_excel': 'Download Excel Template',
    'file.upload.open_google_sheets': 'Open Google Sheets',
    'file.upload.processing': 'Processing...',
    'file.upload.select_file': 'Select File',
    'file.upload.supported_formats': 'CSV, Excel (.xlsx, .xls)',
    'file.preview.title': 'File Data Preview',
    'file.preview.confirm': 'Confirm',
    'file.preview.cancel': 'Cancel',
    'file.preview.valid': 'Valid',
    'file.preview.invalid': 'Invalid',
    'file.preview.row': 'Row',
    'file.preview.name': 'Name',
    'file.preview.birthday': 'Birthday',
    'file.preview.cake_type': 'Cake Type',
    'file.preview.status': 'Status',
    'file.success.employees_added': 'employees added',
    'file.errors.insufficient_columns': 'Insufficient columns',
    'file.errors.name_required': 'Name is required',
    'file.errors.birthday_required': 'Birthday is required',
    'file.errors.invalid_birthday': 'Invalid birthday',
    'file.errors.cake_type_required': 'Cake type is required',
    'file.errors.invalid_file_type': 'Invalid file type. Please select a CSV or Excel file.',
    'file.errors.csv_parse_error': 'Error parsing CSV file',
    'file.errors.excel_parse_error': 'Error parsing Excel file',
    'file.errors.read_error': 'Error reading file',
    'file.errors.no_valid_rows': 'No valid rows found',
    'file.errors.unknown_error': 'Unknown error',
    'file.errors.excel_import_error': 'Error importing Excel library',
    'file.errors.download_error': 'Error downloading template',
    
    // Subscription System
    'subscription.loading': 'Loading data...',
    'subscription.steps.company': 'Company Information',
    'subscription.steps.employees': 'Employees',
    'subscription.steps.subscription': 'Subscription',
    'subscription.steps.payment': 'Payment',
    'subscription.company.title': 'Company Information',
    'subscription.company.name': 'Company Name',
    'subscription.company.contact_name': 'Contact Person Name',
    'subscription.company.email': 'Email',
    'subscription.company.phone': 'Phone Number',
    'subscription.company.address': 'Delivery Address',
    'subscription.employees.title': 'Employees',
    'subscription.employees.file_upload': 'Upload File',
    'subscription.employees.add': 'Add Employee',
    'subscription.employees.employee': 'Employee',
    'subscription.employees.remove': 'Remove',
    'subscription.employees.name': 'Name',
    'subscription.employees.birthday': 'Birthday',
    'subscription.employees.birthday_hint': 'Click the field to select a date',
    'subscription.employees.cake_type': 'Cake Type',
    'subscription.employees.cake_size': 'Cake Size',
    'subscription.employees.dietary': 'Dietary Restrictions',
    'subscription.employees.notes': 'Special Notes',
    'subscription.navigation.back': 'Back',
    'subscription.navigation.next': 'Next',
    'subscription.navigation.submit': 'Submit Subscription',
    'subscription.navigation.submitting': 'Submitting...',
    'subscription.success.title': 'Thank you for registering!',
    'subscription.success.message': 'We have received your subscription request. We will contact you within 24 hours to discuss payment and next steps.',
    'subscription.success.back_home': 'Back to Homepage',
    'subscription.success.view_subscriptions': 'View Subscriptions (Admin)',
    'subscription.success.employees_added': 'employees added',
    'subscription.errors.company_name_required': 'Company name is required',
    'subscription.errors.invalid_email': 'Invalid email address',
    'subscription.errors.invalid_phone': 'Invalid phone number',
    'subscription.errors.address_required': 'Delivery address is required',
    'subscription.errors.no_employees': 'At least one employee is required',
    'subscription.errors.employee_name_required': 'Employee name is required',
    'subscription.errors.birthday_required': 'Birthday is required',
    'subscription.errors.invalid_birthday': 'Invalid birthday',
    'subscription.errors.cake_type_required': 'Cake type is required',
    'subscription.errors.tier_required': 'Please select a subscription tier',
    'subscription.errors.submission_failed': 'Submission failed. Please try again.',
    
    // Cake Types
    'cake.rosakaka_ljos_sukkuladi': 'Rose cake light chocolate',
    'cake.rosakaka_dokkt_sukkuladi': 'Rose cake dark chocolate',
    'cake.skuffukaka_bakka': 'Sheet cake',
    'cake.jardaberja': 'Strawberry',
    'cake.sitronuost': 'Lemon cheese',
    'cake.biscoff': 'Biscoff',
    'cake.daim': 'Daim',
    'cake.tiramisu': 'Tiramisu',
    'cake.sukkuladi_karamellukremi': 'Chocolate with caramel cream',
    'cake.sukkuladi_sukkuladikremi': 'Chocolate with chocolate cream',
    
    // Payment step
    'subscription.payment.title': 'Payment',
    'subscription.payment.summary': 'Order Summary',
    'subscription.payment.company': 'Company',
    'subscription.payment.tier': 'Subscription Tier',
    'subscription.payment.employee_count': 'Number of Employees',
    'subscription.payment.monthly_cost': 'Monthly Cost',
    'subscription.payment.method': 'Payment Method',
    'subscription.payment.aur.title': 'Aur Payment',
    'subscription.payment.aur.description': 'Payment will be sent to your phone number: {phone}',
    'subscription.payment.aur.sms_note': 'You will receive an SMS with a link to complete the payment',
    'subscription.payment.bank_transfer.title': 'Bank Transfer',
    'subscription.payment.bank_transfer.description': 'Get bank details and unique reference number for payment',
    'subscription.payment.bank_transfer.activation_note': 'Subscription will be activated once payment is confirmed',
    'subscription.payment.bank_transfer.success_message': 'Bank details have been generated. Please complete the bank transfer to activate your subscription.',
    'subscription.payment.bank_transfer.instructions': 'Bank Transfer Instructions',
    'subscription.payment.bank_transfer.bank_name': 'Bank',
    'subscription.payment.bank_transfer.account_number': 'Account Number',
    'subscription.payment.bank_transfer.reference': 'Reference Number',
    'subscription.payment.bank_transfer.amount': 'Amount',
    'subscription.payment.bank_transfer.note': 'Please complete the bank transfer. Your subscription will be activated once payment is confirmed.',
    'subscription.payment.bank_transfer.success_title': 'Bank Details Generated!',
    'subscription.payment.terms': 'I agree to pay monthly fees for StraxKaka service and understand that I can cancel anytime.',
    'subscription.payment.success_message': 'Payment request has been sent to your phone number. Please complete the payment to activate your subscription.',
    'subscription.payment.success_title': 'Payment Request Sent!',
    'subscription.payment.phone_number': 'Phone Number',
    'subscription.navigation.processing': 'Processing...',
    'subscription.navigation.pay_now': 'Pay Now',
    'subscription.hero.title': 'Start Your StraxKaka Subscription',
    'subscription.hero.subtitle': 'Never forget a birthday again - we take care of it for you',
    'subscription.features.automatic': 'Automatic Reminders',
    'subscription.features.automatic_desc': 'We remember all birthdays for you',
    'subscription.features.delivery': 'Delivery',
    'subscription.features.delivery_desc': 'Cakes delivered directly to your workplace',
    'subscription.features.simple': 'Simple',
    'subscription.features.simple_desc': 'No hassle - just great service',
    
    // Pricing
    'pricing.title': 'Pricing',
    'pricing.subtitle': 'Monthly subscription + cake costs',
    'pricing.simple.title': 'Simple Pricing',
    'pricing.simple.subtitle': 'Choose the perfect plan for your company size',
    'pricing.little.title': 'Little Company',
    'pricing.little.price': '15,000 ISK',
    'pricing.little.billing': 'per month + cake costs',
    'pricing.little.description': 'Perfect for 1-25 employees',
    'pricing.medium.title': 'Medium Company',
    'pricing.medium.description': 'Perfect for 26-50 employees',
    'pricing.large.title': 'Large Company',
    'pricing.large.description': 'Perfect for 51+ employees',
    'pricing.little_company': 'Little Company (1-25 employees)',
    'pricing.little_company_price': '15,000 ISK per month + cake costs',
    'pricing.contact_for_pricing': 'Contact for pricing',
    'pricing.recommended': 'Recommended',
    'pricing.per_month': 'per month',
    'pricing.employees': 'employees',
    'pricing.suitable': 'Suitable for your company',
    'pricing.not_suitable': 'Not suitable for your company',
    'pricing.selected': 'Selected',
    'pricing.select': 'Select',
    'pricing.for_your_company': 'For your company',
    'pricing.for': 'For',
    'pricing.disclaimer': 'All prices include 24% VAT. No setup fee. Cancel anytime.',
    'pricing.tiers.small.name': 'Small',
    'pricing.tiers.small.description': 'Perfect for small teams',
    'pricing.tiers.medium.name': 'Medium',
    'pricing.tiers.medium.description': 'Ideal for growing companies',
    'pricing.tiers.large.name': 'Large',
    'pricing.tiers.large.description': 'Great for established businesses',
    'pricing.tiers.enterprise.name': 'Enterprise',
    'pricing.tiers.enterprise.description': 'Custom pricing for large organizations',
    'pricing.tiers.enterprise.price': 'Custom',
    
    // Additional pricing for services page
    'pricing.small.title': 'Small',
    'pricing.small.price': 'Custom',
    'pricing.small.description': 'For under 50 employees',
    'pricing.small.billing': 'Billed per birthday',
    'pricing.starter.title': 'Medium',
    'pricing.starter.price': '60,000 ISK',
    'pricing.starter.description': 'For 50+ employees',
    'pricing.starter.billing': 'Billed per birthday (~12,600 ISK each)',
    'pricing.professional.title': 'Large',
    'pricing.professional.price': '120,000 ISK',
    'pricing.professional.description': 'For 100+ employees',
    'pricing.professional.billing': 'Billed per birthday',
    'pricing.business.title': 'Enterprise',
    'pricing.business.price': 'Custom',
    'pricing.business.description': 'For 200+ employees',
    'pricing.business.billing': 'Billed per birthday (~12,600 ISK each)',
    'pricing.enterprise.title': 'Enterprise',
    'pricing.enterprise.price': 'Custom',
    'pricing.enterprise.description': 'For 200+ employees',
    'pricing.enterprise.billing': 'Billed per birthday (~12,600 ISK each)',
    
    // Dashboard
    'dashboard.loading': 'Loading data...',
    'dashboard.title': 'Admin Dashboard',
    'dashboard.subtitle': 'View and manage subscriptions and payments',
    'dashboard.stats.companies': 'Companies',
    'dashboard.stats.active': 'Active Subscriptions',
    'dashboard.stats.pending': 'Pending Payment',
    'dashboard.stats.revenue': 'Monthly Revenue',
    'dashboard.companies.title': 'Companies',
    'dashboard.companies.company': 'Company',
    'dashboard.companies.status': 'Status',
    'dashboard.companies.monthly_cost': 'Monthly Cost',
    'dashboard.companies.employees': 'Employees',
    'dashboard.companies.next_payment': 'Next Payment',
    'dashboard.payments.title': 'Recent Payments',
    'dashboard.payments.order': 'Order',
    'dashboard.payments.amount': 'Amount',
    'dashboard.payments.status': 'Status',
    'dashboard.payments.date': 'Date',
    'dashboard.status.active': 'Active',
    'dashboard.status.pending_payment': 'Pending Payment',
    'dashboard.status.suspended': 'Suspended',
    'dashboard.status.cancelled': 'Cancelled',
    'dashboard.payment_status.completed': 'Completed',
    'dashboard.payment_status.processing': 'Processing',
    'dashboard.payment_status.failed': 'Failed',
    'dashboard.payment_status.pending': 'Pending',
    
    // About page
    'about.hero.title': 'About Us',
    'about.hero.subtitle': 'We believe that everyone should be celebrated',
    'about.founder.title': 'Founder of StraxKaka',
    'about.founder.caption': 'Founder of StraxKaka',
    'about.intro.title': 'The Problem',
    'about.intro.desc': 'In HR departments there can be enough to do - you need to remember birthday dates, order cakes, pick up and present them. This can increase stress or even be forgotten.',
    'about.solution.title': 'Straxkaka is the solution',
    'about.solution.desc': 'We handle the entire process, you don\'t need to lift a finger. Celebrating each other has never been so easy and fun',
    'about.why.title': 'Why Straxkaka?',
    'about.why.focus.title': 'We at Straxkaka focus on celebrating each other',
    'about.why.focus.desc': 'We believe that such events matter greatly for workplace culture. The workplace is much more than just work, it\'s a place where we spend a large part of our lives. We should celebrate our colleagues, because good workplace culture matters greatly.',
    'about.promise.title': 'Our Promise',
    'about.promise.desc': 'We partner with trusted bakeries that use high-quality ingredients. The cakes are baked with care and delivered on time – always ready to delight.',
    'about.future.title': 'The Future',
    'about.future.desc': 'Straxkaka is more than just cake. We are building a future of workplace culture where no birthday is forgotten and no employee feels overlooked.',
    'about.team.title': 'Our Team',
    'about.team.desc': 'Hi, I\'m Bjarki, the founder of Straxkaka. I\'m 20 years old and started this company with a simple goal: to make birthdays at work easier and more meaningful. I know how stressful it can be when someone\'s birthday is forgotten, so I wanted to create a service where no one has to worry — the cake just arrives on time. I work closely with local bakeries to make sure every delivery is smooth, and I\'m dedicated to keeping the process reliable, friendly, and stress-free.',
    'about.cta.title': 'Ready to get started?',
    'about.cta.subtitle': 'Contact us and find out how Straxkaka can improve the atmosphere at your workplace.',
    'about.cta.subscribe': 'Start Subscription',
    'about.cta.contact': 'Contact Us',
    
    // Services page
    'services.hero.title': 'Our Services',
    'services.hero.subtitle': 'Everything you need to never forget employee birthdays',
    'services.process.title': 'How does it work?',
    'services.process.subtitle': 'Simple process in 4 steps',
    'services.detailed.title': 'What We Offer',
    'services.detailed.subtitle': 'Everything you need for perfect birthday management',
    'services.benefits.title': 'StraxKaka Benefits',
    'services.benefits.subtitle': 'Why do companies choose StraxKaka?',
    'services.cta.title': 'Ready to get started?',
    'services.cta.subtitle': 'Contact us today for a free consultation.',
    'services.cta.subscribe': 'Start Subscription',
    'services.cta.contact': 'Contact Us',
    
    // Services features
    'services.registration.feature1': 'Secure HR system connection',
    'services.registration.feature2': 'Automatic data transfer',
    'services.registration.feature3': 'GDPR compliant',
    'services.registration.feature4': '24/7 protection',
    'services.ai.desc': 'Our system automatically orders cakes 3 days before birthdays and sends notifications to you and the employee.',
    'services.ai.feature1': 'Automatic cake ordering',
    'services.ai.feature2': 'Birthday notifications',
    'services.ai.feature3': 'Customized messages',
    'services.ai.feature4': 'Quality management',
    'services.delivery.desc': 'We work with the best bakeries in Iceland and ensure delivery to the workplace on time.',
    'services.delivery.feature1': 'Working with best bakeries',
    'services.delivery.feature2': 'Reliable delivery',
    'services.delivery.feature3': 'Multiple options',
    'services.delivery.feature4': 'Quality assurance',
    'services.cakes.title': 'Cakes We Offer',
    'services.cakes.subtitle': 'Most cakes are the same size - perfect for birthdays',
    'services.cakes.delivery_included': 'Delivery included',
    'services.cakes.rose_light': 'Rose Cake Light Chocolate',
    'services.cakes.rose_dark': 'Rose Cake Dark Chocolate',
    'services.cakes.skuffu': 'Skúffukaka on Tray',
    'services.cakes.strawberry': 'Strawberry',
    'services.cakes.lemon_cheese': 'Lemon Cheese',
    'services.cakes.biscoff': 'Biscoff',
    'services.cakes.daim': 'Daim',
    'services.cakes.tiramisu': 'Tiramisu',
    'services.cakes.chocolate_caramel': 'Chocolate with Caramel Cream',
    'services.cakes.chocolate_cream': 'Chocolate with Chocolate Cream',
    
    // Contact page
    'contact.hero.title': 'Contact Us',
    'contact.hero.subtitle': 'Contact us and find out how StraxKaka can improve the atmosphere at your workplace',
    'contact.info.title': 'Get in Touch',
    'contact.info.subtitle': 'Easy to reach us',
    'contact.info.email.desc': 'Send us an email for all inquiries',
    'contact.info.phone.desc': 'Call us on weekdays 9:00-17:00',
    'contact.support.email.title': 'Email Support',
    'contact.support.email.desc': 'Send us an email for general inquiries, support, or business questions',
    'contact.support.email.action': 'Send Email',
    'contact.support.phone.title': 'Phone Support',
    'contact.support.phone.desc': 'Call us for immediate assistance or urgent matters',
    'contact.support.phone.action': 'Call Now',
    'contact.support.hours.title': 'Business Hours',
    'contact.support.hours.desc': 'Monday - Friday: 9:00 AM - 5:00 PM (GMT)',
    'contact.why.title': 'Why StraxKaka?',
    'contact.why.subtitle': 'We are here to help you improve workplace service',
    'contact.why.fast.title': 'Quick Response',
    'contact.why.fast.desc': 'We respond to all inquiries within 24 hours',
    'contact.why.reliable.title': 'Reliable Service',
    'contact.why.reliable.desc': 'No forgotten birthdays with our system',
    'contact.why.personal.title': 'Personal Service',
    'contact.why.personal.desc': 'We serve each company in a unique way',
    
    // Blog
    'blog.article.title': 'The Sweet Secret to a Happier Workplace: Never Forget a Birthday Again',
    'blog.article.excerpt': 'Learn how workplace celebrations can boost morale, increase happiness, and save time for HR departments.',
    'blog.article.read_more': 'Read Article',
    'blog.title': 'Blog',
    'blog.section.title': 'Article',
    'blog.section.subtitle': 'How workplace celebrations can boost morale and save time',
    'blog.hero.title': 'The Sweet Secret to a Happier Workplace: Never Forget a Birthday Again',
    'blog.hero.subtitle': 'How workplace celebrations can boost morale and save time',
    'blog.content.intro': 'Workplaces are more than just offices where tasks get done—they\'re communities where people spend a significant part of their lives. In these spaces, feeling welcomed, appreciated, and valued is essential not only for happiness but also for productivity, teamwork, and morale. One of the simplest yet most impactful ways to cultivate this culture? Celebrating birthdays.',
    'blog.content.why_matter.title': 'Why Celebrations Matter',
    'blog.content.why_matter.desc': 'It might seem small, but acknowledging milestones like birthdays sends a powerful message: "You matter here." Regular celebrations foster togetherness, strengthen relationships between colleagues, and build a sense of belonging. When employees feel valued, they\'re more motivated, collaborative, and engaged. In short, a small gesture can create big ripples of positivity throughout the workplace.',
    'blog.content.cost_forgetting.title': 'The Cost of Forgetting',
    'blog.content.cost_forgetting.desc': 'On the flip side, forgetting a birthday isn\'t just awkward—it can be detrimental. A forgotten birthday can create stressful moments, misunderstandings, and even resentment, subtly impacting morale and the overall workplace culture. HR staff may try their best to remember, but in busy offices with many employees, it\'s easy to overlook someone\'s special day. Even when remembered, the process of ordering, coordinating, and serving a cake can be stressful and time-consuming.',
    'blog.content.enter_straxkaka.title': 'Enter StraxKaka',
    'blog.content.enter_straxkaka.desc': 'That\'s where StraxKaka comes in. Our service ensures no birthday ever goes unnoticed, taking the stress off HR and managers. With automated reminders and hassle-free cake delivery, we handle everything so that employees feel valued and celebrated—without anyone lifting a finger.',
    'blog.content.investment.intro': 'By investing in a service like StraxKaka, companies are investing in:',
    'blog.content.investment.happiness': 'Employee happiness: Small gestures like birthday celebrations improve daily morale.',
    'blog.content.investment.cohesion': 'Team cohesion: Sharing celebrations fosters teamwork and strengthens bonds.',
    'blog.content.investment.productivity': 'Productivity: Happy employees are motivated employees, leading to better results.',
    'blog.content.investment.efficiency': 'HR efficiency: Automating celebrations frees up time and reduces stress.',
    'blog.content.more_than_cake.title': 'More Than Just Cake',
    'blog.content.more_than_cake.desc': 'It\'s not just about the cake—it\'s about creating a culture of appreciation. Each celebration is a reminder that every team member matters, building a workplace where people look forward to coming in, engage more deeply, and collaborate effectively.',
    'blog.content.conclusion.main': 'StraxKaka isn\'t just about remembering birthdays. It\'s about sweetening the culture, turning ordinary workdays into moments of connection, joy, and recognition.',
    'blog.content.conclusion.cta': 'Invest in your team\'s happiness. Invest in StraxKaka. Because when birthdays are never forgotten, your culture becomes a little sweeter every day.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('is');
  const [isHydrated, setIsHydrated] = useState(false);

  // Handle hydration
  useEffect(() => {
    setIsHydrated(true);
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'is' || savedLanguage === 'en')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    // Use the current language state
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isHydrated }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
